package cyclops.collections.clojure;

import java.util.AbstractList;
import java.util.Collection;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import java.util.stream.Stream;

import com.aol.cyclops2.data.collections.extensions.CollectionX;
import com.aol.cyclops2.data.collections.extensions.lazy.immutable.LazyPVectorX;
import com.aol.cyclops2.types.Unwrapable;
import cyclops.collections.immutable.VectorX;
import cyclops.function.Reducer;
import cyclops.stream.ReactiveSeq;
import org.jooq.lambda.tuple.Tuple2;
import org.pcollections.PVector;


import clojure.lang.PersistentVector;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.experimental.Wither;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class ClojureVectorX<T> extends AbstractList<T> implements PVector<T>, Unwrapable {
    public static <T> VectorX<T> copyFromCollection(CollectionX<T> vec) {
        return ClojureVectorX.<T>empty()
                .plusAll(vec);

    }
    @Override
    public <R> R unwrap() {
        return (R)vector;
    }
    /**
     * Create a LazyPVectorX from a Stream
     * 
     * @param stream to construct a LazyQueueX from
     * @return LazyPVectorX
     */
    public static <T> LazyPVectorX<T> fromStream(Stream<T> stream) {
        Reducer<PVector<T>> v = toPVector();
        return new LazyPVectorX<T>(null, ReactiveSeq.fromStream(stream),v);
    }

    /**
     * Create a LazyPVectorX that contains the Integers between start and end
     * 
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyPVectorX<Integer> range(int start, int end) {
        return fromStream(ReactiveSeq.range(start, end));
    }

    /**
     * Create a LazyPVectorX that contains the Longs between start and end
     * 
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyPVectorX<Long> rangeLong(long start, long end) {
        return fromStream(ReactiveSeq.rangeLong(start, end));
    }

    /**
     * Unfold a function into a ListX
     * 
     * <pre>
     * {@code 
     *  LazyPVectorX.unfold(1,i->i<=6 ? Optional.of(Tuple.tuple(i,i+1)) : Optional.empty());
     * 
     * //(1,2,3,4,5)
     * 
     * }</pre>
     * 
     * @param seed Initial value 
     * @param unfolder Iteratively applied function, terminated by an empty Optional
     * @return ListX generated by unfolder function
     */
    public static <U, T> LazyPVectorX<T> unfold(U seed, Function<? super U, Optional<Tuple2<T, U>>> unfolder) {
        return fromStream(ReactiveSeq.unfold(seed, unfolder));
    }

    /**
     * Generate a LazyPVectorX from the provided Supplier up to the provided limit number of times
     * 
     * @param limit Max number of elements to generate
     * @param s Supplier to generate ListX elements
     * @return ListX generated from the provided Supplier
     */
    public static <T> LazyPVectorX<T> generate(long limit, Supplier<T> s) {

        return fromStream(ReactiveSeq.generate(s)
                                      .limit(limit));
    }

    /**
     * Create a LazyPVectorX by iterative application of a function to an initial element up to the supplied limit number of times
     * 
     * @param limit Max number of elements to generate
     * @param seed Initial element
     * @param f Iteratively applied to each element to generate the next element
     * @return ListX generated by iterative application
     */
    public static <T> LazyPVectorX<T> iterate(long limit, final T seed, final UnaryOperator<T> f) {
        return fromStream(ReactiveSeq.iterate(seed, f)
                                      .limit(limit));
    }

    /**
     * <pre>
     * {@code 
     * PVector<Integer> q = JSPVector.<Integer>toPVector()
                                     .mapReduce(Stream.of(1,2,3,4));
     * 
     * }
     * </pre>
     * @return Reducer for PVector
     */
    public static <T> Reducer<PVector<T>> toPVector() {
        return Reducer.<PVector<T>> of(ClojureVectorX.emptyPVector(), (final PVector<T> a) -> b -> a.plusAll(b), (final T x) -> ClojureVectorX.singleton(x));
    }
    
   
    public static <T> ClojureVectorX<T> fromVector(PersistentVector vector){
        return new ClojureVectorX<>(vector);
    }
    
    public static <T> ClojureVectorX<T> emptyPVector(){
        return new ClojureVectorX<>(PersistentVector.EMPTY);
    }
    public static <T> LazyPVectorX<T> empty(){
        return fromPVector(new ClojureVectorX<>(PersistentVector.EMPTY), toPVector());
    }
    public static <T> LazyPVectorX<T> singleton(T t){
        PersistentVector result = PersistentVector.EMPTY;
        return fromPVector(new ClojureVectorX<>(result.cons(t)), toPVector());
    }
    public static <T> LazyPVectorX<T> of(T... t){
        PersistentVector vb = PersistentVector.create(t);
        
        return fromPVector(new ClojureVectorX<>(vb), toPVector());
    }
    public static <T> LazyPVectorX<T> PVector(PersistentVector q) {
        return fromPVector(new ClojureVectorX<T>(q), toPVector());
    }
    @SafeVarargs
    public static <T> LazyPVectorX<T> PVector(T... elements){
        return fromPVector(of(elements),toPVector());
    }
    @Wither
    private final PersistentVector vector;

    @Override
    public ClojureVectorX<T> plus(T e) {
        return withVector(vector.cons(e));
    }

    @Override
    public ClojureVectorX<T> plusAll(Collection<? extends T> list) {
        PersistentVector use = vector;
        for(T next : list)
            use = use.cons(next);
        return withVector(use);
     }
 

    @Override
    public ClojureVectorX<T> with(int i, T e) {
        if(i<0 || i>size())
            throw new IndexOutOfBoundsException("Index " + i + " is out of bounds - size : " + size());
        return withVector(vector.assocN(i,e));
    }

    @Override
    public PVector<T>  plus(int i, T e){
        if(size()==0 || i==size())
            return plus(e);
       ReactiveSeq<T> flux = ReactiveSeq.fromIterable(vector);
       ReactiveSeq<T> inserted = flux.insertAt(i, e);
       return fromStream(inserted);

       
    }
    private static <T> LazyPVectorX<T> fromPVector(PVector<T> vec, Reducer<PVector<T>> pVectorReducer) {
        return new LazyPVectorX<T>(vec,null, pVectorReducer);
    }
    @Override
    public PVector<T> plusAll(int i, Collection<? extends T> list) {
        ReactiveSeq<T> flux = fromPVector(this,toPVector()).stream();
        ReactiveSeq<T> inserted = flux.insertAtS(i, (Stream<T>)list.stream());
        
        return fromStream(inserted);
    }

    @Override
    public PVector<T> minus(Object e) {
     
        return fromPVector(this,toPVector()).filter(i->!Objects.equals(i,e));
    }

    @Override
    public PVector<T> minusAll(Collection<?> list) {
        return (VectorX<T>)fromPVector(this,toPVector()).removeAllI((Iterable<T>)list);
    }
    
    public ClojureVectorX<T> tail(){
        return withVector(PersistentVector.create(vector.tail));
    }
    public T head(){
        return (T)vector.nth(0);
    }

    @Override
    public PVector<T> minus(int i) {
      
        return fromPVector(this,toPVector())
                        .zipWithIndex()
                        .filter(t->t.v2.intValue()!=i)
                        .map(t->t.v1);
    }

    @Override
    public PVector<T> subList(int start, int end) {
        return fromPVector(this,toPVector())
                .skip((long)start)
                .limit(end-start);
        
    }

    @Override
    public T get(int index) {
        return (T)vector.nth(index);
    }

    @Override
    public int size() {
        return vector.size();
    }

   
}
