package com.aol.cyclops.scala.collections;

import java.util.AbstractList;
import java.util.Collection;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import java.util.stream.Stream;

import org.jooq.lambda.tuple.Tuple2;
import org.pcollections.PStack;

import com.aol.cyclops.Reducer;
import com.aol.cyclops.control.ReactiveSeq;
import com.aol.cyclops.reactor.collections.extensions.persistent.LazyPStackX;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.val;
import lombok.experimental.Wither;
import reactor.core.publisher.Flux;
import scala.collection.generic.CanBuildFrom;
import scala.collection.immutable.List;
import scala.collection.immutable.List$;
import scala.collection.mutable.Builder;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class ScalaPStack<T> extends AbstractList<T>implements PStack<T> {

    /**
     * Create a LazyPStackX from a Stream
     * 
     * @param stream to construct a LazyQueueX from
     * @return LazyPStackX
     */
    public static <T> LazyPStackX<T> fromStream(Stream<T> stream) {
        return new LazyPStackX<T>(
                                  Flux.from(ReactiveSeq.fromStream(stream)), toPStack());
    }

    /**
     * Create a LazyPStackX that contains the Integers between start and end
     * 
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyPStackX<Integer> range(int start, int end) {
        return fromStream(ReactiveSeq.range(start, end));
    }

    /**
     * Create a LazyPStackX that contains the Longs between start and end
     * 
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyPStackX<Long> rangeLong(long start, long end) {
        return fromStream(ReactiveSeq.rangeLong(start, end));
    }

    /**
     * Unfold a function into a ListX
     * 
     * <pre>
     * {@code 
     *  LazyPStackX.unfold(1,i->i<=6 ? Optional.of(Tuple.tuple(i,i+1)) : Optional.empty());
     * 
     * //(1,2,3,4,5)
     * 
     * }</pre>
     * 
     * @param seed Initial value 
     * @param unfolder Iteratively applied function, terminated by an empty Optional
     * @return ListX generated by unfolder function
     */
    public static <U, T> LazyPStackX<T> unfold(U seed, Function<? super U, Optional<Tuple2<T, U>>> unfolder) {
        return fromStream(ReactiveSeq.unfold(seed, unfolder));
    }

    /**
     * Generate a LazyPStackX from the provided Supplier up to the provided limit number of times
     * 
     * @param limit Max number of elements to generate
     * @param s Supplier to generate ListX elements
     * @return ListX generated from the provided Supplier
     */
    public static <T> LazyPStackX<T> generate(long limit, Supplier<T> s) {

        return fromStream(ReactiveSeq.generate(s)
                                     .limit(limit));
    }

    /**
     * Create a LazyPStackX by iterative application of a function to an initial element up to the supplied limit number of times
     * 
     * @param limit Max number of elements to generate
     * @param seed Initial element
     * @param f Iteratively applied to each element to generate the next element
     * @return ListX generated by iterative application
     */
    public static <T> LazyPStackX<T> iterate(long limit, final T seed, final UnaryOperator<T> f) {
        return fromStream(ReactiveSeq.iterate(seed, f)
                                     .limit(limit));
    }

    /**
     * <pre>
     * {@code 
     * PStack<Integer> q = JSPStack.<Integer>toPStack()
                                     .mapReduce(Stream.of(1,2,3,4));
     * 
     * }
     * </pre>
     * @return Reducer for PStack
     */
    public static <T> Reducer<PStack<T>> toPStack() {
        return Reducer.<PStack<T>> of(ScalaPStack.emptyPStack(), (final PStack<T> a) -> b -> a.plusAll(b),
                                      (final T x) -> ScalaPStack.singleton(x));
    }

    public static <T> ScalaPStack<T> fromList(List<T> list) {
        return new ScalaPStack<>(
                                 list);
    }

    public static <T> ScalaPStack<T> emptyPStack() {

        return new ScalaPStack<>(
                                 List$.MODULE$.empty());
    }

    public static <T> LazyPStackX<T> empty() {
        return LazyPStackX.fromPStack(new ScalaPStack<>(
                                                        List$.MODULE$.empty()),
                                      toPStack());
    }

    public static <T> LazyPStackX<T> singleton(T t) {
        List<T> result = List$.MODULE$.empty();
        return LazyPStackX.fromPStack(new ScalaPStack<>(
                                                        result.$colon$colon(t)),
                                      toPStack());
    }

    public static <T> LazyPStackX<T> of(T... t) {

        Builder<T, List<T>> lb = List$.MODULE$.newBuilder();
        for (T next : t)
            lb.$plus$eq(next);
        List<T> vec = lb.result();
        return LazyPStackX.fromPStack(new ScalaPStack<>(
                                                        vec),
                                      toPStack());
    }

    public static <T> LazyPStackX<T> PStack(List<T> q) {
        return LazyPStackX.fromPStack(new ScalaPStack<T>(
                                                         q),
                                      toPStack());
    }

    @SafeVarargs
    public static <T> LazyPStackX<T> PStack(T... elements) {
        return LazyPStackX.fromPStack(of(elements), toPStack());
    }

    @Wither
    private final List<T> list;

    @Override
    public ScalaPStack<T> plus(T e) {
        return withList(list.$colon$colon(e));
    }

    @Override
    public ScalaPStack<T> plusAll(Collection<? extends T> l) {
        List<T> vec = list;
        for (T next : l) {
            vec = vec.$colon$colon(next);
        }

        return withList(vec);
    }

    @Override
    public ScalaPStack<T> with(int i, T e) {
        if (i < 0 || i > size())
            throw new IndexOutOfBoundsException(
                                                "Index " + i + " is out of bounds - size : " + size());

        return withList(list.drop(i + 1)
                            .$colon$colon(e)
                            .$colon$colon$colon((List<T>)list.dropRight(size()-i)));
    }

    @Override
    public ScalaPStack<T> plus(int i, T e) {
        if (i < 0 || i > size())
            throw new IndexOutOfBoundsException(
                                                "Index " + i + " is out of bounds - size : " + size());
        if (i == 0)
            return withList(list.$colon$colon(e));
        final CanBuildFrom<List<?>, T, List<T>> builder = List.<T> canBuildFrom();
        final CanBuildFrom<List<T>, T, List<T>> builder2 = (CanBuildFrom) builder;
        if (i == size() - 1) {

            return withList(list.$colon$plus(e, builder2));
        }

        val frontBack = list.splitAt(i);

        val back = frontBack._2.$colon$colon(e);
        return withList(back.$colon$colon$colon(frontBack._1));

    }

    @Override
    public ScalaPStack<T> plusAll(int i, Collection<? extends T> l) {

        if (i < 0 || i > size())
            throw new IndexOutOfBoundsException(
                                                "Index " + i + " is out of bounds - size : " + size());
        List<T> l2 = List$.MODULE$.empty();
        for (T next : l) {
            l2 = l2.$colon$colon(next);
        }
        if (i == 0)
            return withList(list.$colon$colon$colon(l2));
        final CanBuildFrom<List<?>, T, List<T>> builder = List.<T> canBuildFrom();
        final CanBuildFrom<List<T>, T, List<T>> builder2 = (CanBuildFrom) builder;
        if (i == size() - 1) {

            return withList(l2.$colon$colon$colon(list));
        }

        val frontBack = list.splitAt(i);

        val back = frontBack._2.$colon$colon$colon(l2);
        return withList(back.$colon$colon$colon(frontBack._1));
    }

    @Override
    public PStack<T> minus(Object e) {
        return LazyPStackX.fromPStack(this, toPStack())
                          .filter(i -> !Objects.equals(i, e));
    }

    @Override
    public PStack<T> minusAll(Collection<?> list) {
        return LazyPStackX.fromPStack(this, toPStack())
                          .removeAll((Iterable<T>) list);
    }

    public ScalaPStack<T> tail() {
        return withList((List<T>) list.tail());
    }

    public T head() {
        return list.head();
    }

    @Override
    public ScalaPStack<T> minus(int i) {

        if (i < 0 || i > size())
            throw new IndexOutOfBoundsException(
                                                "Index " + i + " is out of bounds - size : " + size());
        if (i == 0)
            return withList(list.drop(1));
        if (i == size() - 1)
            return withList(list.dropRight(1)
                                .toList());
        val frontBack = list.splitAt(i);
        final CanBuildFrom<List<?>, T, List<T>> builder = List.<T> canBuildFrom();
        final CanBuildFrom<List<T>, T, List<T>> builder2 = (CanBuildFrom) builder;
        val front = frontBack._1;

        List<T> result = (List<T>) front.$plus$plus(frontBack._2.drop(1), builder2);

        return withList(result);
    }

    @Override
    public ScalaPStack<T> subList(int start, int end) {

        return withList(list.drop(start)
                            .take(end - start));
    }

    @Override
    public T get(int index) {
        return list.apply(index);
    }

    @Override
    public int size() {
        return list.size();
    }

    @Override
    public ScalaPStack<T> subList(int start) {
        return withList(list.drop(start));
    }

}
