package cyclops.companion.functionaljava;

import cyclops.function.Fn3;
import cyclops.function.Fn4;
import fj.data.Reader;
import lombok.experimental.UtilityClass;

import java.util.function.BiFunction;
import java.util.function.Function;

/**
 * Utility class for working with JDK Optionals
 *
 * @author johnmcclean
 *
 */
@UtilityClass
public class Readers {

    /**
     * Perform a For Comprehension over a Option, accepting 3 generating function.
     * This results in a four level nested internal iteration over the provided Options.
     *
     *  <pre>
     * {@code
     *
     *   import static com.oath.cyclops.reactor.Options.forEach4;
     *
    forEach4(Option.just(1),
    a-> Option.just(a+1),
    (a,b) -> Option.<Integer>just(a+b),
    a                  (a,b,c) -> Option.<Integer>just(a+b+c),
    Tuple::tuple)
     *
     * }
     * </pre>
     *
     * @param value1 top level Option
     * @param value2 Nested Option
     * @param value3 Nested Option
     * @param value4 Nested Option
     * @param yieldingFunction Generates a result per combination
     * @return Option with a combined value generated by the yielding function
     */
    public static <T,T1, T2, T3, R1, R2, R3, R> Reader<T,R> forEach4(Reader<T,? extends T1> value1,
                                                                     Function<? super T1, ? extends Reader<T,R1>> value2,
                                                                     BiFunction<? super T1, ? super R1, ? extends Reader<T,R2>> value3,
                                                                     Fn3<? super T1, ? super R1, ? super R2, ? extends Reader<T,R3>> value4,
                                                                     Fn4<? super T1, ? super R1, ? super R2, ? super R3, ? extends R> yieldingFunction) {

        return value1.bind(in -> {

            Reader<T,R1> a = value2.apply(in);
            return a.bind(ina -> {
                Reader<T,R2> b = value3.apply(in,ina);
                return b.bind(inb -> {
                    Reader<T,R3> c = value4.apply(in,ina,inb);
                    return c.map(in2 -> yieldingFunction.apply(in, ina, inb, in2));
                });

            });

        });

    }


    /**
     * Perform a For Comprehension over a Option, accepting 2 generating function.
     * This results in a three level nested internal iteration over the provided Options.
     *
     *  <pre>
     * {@code
     *
     *   import static com.oath.cyclops.reactor.Options.forEach3;
     *
    forEach3(Option.just(1),
    a-> Option.just(a+1),
    (a,b) -> Option.<Integer>just(a+b),
    Tuple::tuple)
     *
     * }
     * </pre>
     *
     * @param value1 top level Option
     * @param value2 Nested Option
     * @param value3 Nested Option
     * @param yieldingFunction Generates a result per combination
     * @return Option with a combined value generated by the yielding function
     */
    public static <T,T1, T2, R1, R2, R> Reader<T,R> forEach3(Reader<T,? extends T1> value1,
                                                         Function<? super T1, ? extends Reader<T,R1>> value2,
                                                         BiFunction<? super T1, ? super R1, ? extends Reader<T,R2>> value3,
                                                         Fn3<? super T1, ? super R1, ? super R2, ? extends R> yieldingFunction) {

        return value1.bind(in -> {

            Reader<T,R1> a = value2.apply(in);
            return a.bind(ina -> {
                Reader<T,R2> b = value3.apply(in,ina);
                return b.map(in2 -> yieldingFunction.apply(in, ina, in2));
            });


        });

    }



    /**
     * Perform a For Comprehension over a Option, accepting a generating function.
     * This results in a two level nested internal iteration over the provided Options.
     *
     *  <pre>
     * {@code
     *
     *   import static com.oath.cyclops.reactor.Options.forEach;
     *
    forEach(Option.just(1),
    a-> Option.just(a+1),
    Tuple::tuple)
     *
     * }
     * </pre>
     *
     * @param value1 top level Option
     * @param value2 Nested Option
     * @param yieldingFunction Generates a result per combination
     * @return Option with a combined value generated by the yielding function
     */
    public static <T0,T, R1, R> Reader<T0,R> forEach2(Reader<T0,? extends T> value1,
                                                  Function<? super T, Reader<T0,R1>> value2,
                                                BiFunction<? super T, ? super R1, ? extends R> yieldingFunction) {

        return value1.bind(in -> {

            Reader<T0,R1> a = value2.apply(in);
            return a.map(in2 -> yieldingFunction.apply(in,  in2));
        });



    }






}
