package cyclops.collections.dexx;

import java.util.AbstractList;
import java.util.Collection;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import java.util.stream.Stream;

import com.aol.cyclops2.data.collections.extensions.CollectionX;
import com.aol.cyclops2.data.collections.extensions.lazy.immutable.LazyPVectorX;
import cyclops.collections.immutable.VectorX;
import cyclops.function.Reducer;
import cyclops.stream.ReactiveSeq;
import org.jooq.lambda.tuple.Tuple2;
import org.pcollections.PVector;


import com.github.andrewoma.dexx.collection.Builder;
import com.github.andrewoma.dexx.collection.Vector;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.experimental.Wither;
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class DexxVectorX<T> extends AbstractList<T> implements PVector<T> {

    public static <T> VectorX<T> copyFromCollection(CollectionX<T> vec) {

        return DexxVectorX.<T>empty()
                .plusAll(vec);

    }
    /**
     * Create a LazyPVectorX from a Stream
     * 
     * @param stream to construct a LazyQueueX from
     * @return LazyPVectorX
     */
    public static <T> LazyPVectorX<T> fromStream(Stream<T> stream) {
        Reducer<PVector<T>> r = toPVector();
        return new LazyPVectorX<T>(null, ReactiveSeq.fromStream(stream),r);
    }

    /**
     * Create a LazyPVectorX that contains the Integers between start and end
     * 
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyPVectorX<Integer> range(int start, int end) {
        return fromStream(ReactiveSeq.range(start, end));
    }

    /**
     * Create a LazyPVectorX that contains the Longs between start and end
     * 
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyPVectorX<Long> rangeLong(long start, long end) {
        return fromStream(ReactiveSeq.rangeLong(start, end));
    }

    /**
     * Unfold a function into a ListX
     * 
     * <pre>
     * {@code 
     *  LazyPVectorX.unfold(1,i->i<=6 ? Optional.of(Tuple.tuple(i,i+1)) : Optional.empty());
     * 
     * //(1,2,3,4,5)
     * 
     * }</pre>
     * 
     * @param seed Initial value 
     * @param unfolder Iteratively applied function, terminated by an empty Optional
     * @return ListX generated by unfolder function
     */
    public static <U, T> LazyPVectorX<T> unfold(U seed, Function<? super U, Optional<Tuple2<T, U>>> unfolder) {
        return fromStream(ReactiveSeq.unfold(seed, unfolder));
    }

    /**
     * Generate a LazyPVectorX from the provided Supplier up to the provided limit number of times
     * 
     * @param limit Max number of elements to generate
     * @param s Supplier to generate ListX elements
     * @return ListX generated from the provided Supplier
     */
    public static <T> LazyPVectorX<T> generate(long limit, Supplier<T> s) {

        return fromStream(ReactiveSeq.generate(s)
                                      .limit(limit));
    }

    /**
     * Create a LazyPVectorX by iterative application of a function to an initial element up to the supplied limit number of times
     * 
     * @param limit Max number of elements to generate
     * @param seed Initial element
     * @param f Iteratively applied to each element to generate the next element
     * @return ListX generated by iterative application
     */
    public static <T> LazyPVectorX<T> iterate(long limit, final T seed, final UnaryOperator<T> f) {
        return fromStream(ReactiveSeq.iterate(seed, f)
                                      .limit(limit));
    }

    /**
     * <pre>
     * {@code 
     * PVector<Integer> q = JSPVector.<Integer>toPVector()
                                     .mapReduce(Stream.of(1,2,3,4));
     * 
     * }
     * </pre>
     * @return Reducer for PVector
     */
    public static <T> Reducer<PVector<T>> toPVector() {
        return Reducer.<PVector<T>> of(DexxVectorX.emptyPVector(), (final PVector<T> a) -> b -> a.plusAll(b), (final T x) -> DexxVectorX.singleton(x));
    }
    public static <T> Builder<T,Vector<T>> builder(){
        return Vector.<T>factory().newBuilder();
    }
    public static <T> DexxVectorX<T> fromVector(Vector<T> vector){
        return new DexxVectorX<>(vector);
    }
    
    public static <T> DexxVectorX<T> emptyPVector(){
        return new DexxVectorX<>(Vector.empty());
    }
    
    public static <T> LazyPVectorX<T> empty(){
        return fromPVector(new DexxVectorX<>(Vector.empty()), toPVector());
    }
    public static <T> PVector<T> singleton(T t){
        Builder<T, Vector<T>> builder = Vector.<T>factory().newBuilder();
        return fromPVector(new DexxVectorX<>(builder.add(t).build()), toPVector());
    }
    public static <T> LazyPVectorX<T> of(T... t){
        Builder<T, Vector<T>> builder = Vector.<T>factory().newBuilder();
        for(T next : t){
            builder.add(next);
        }
        return fromPVector(new DexxVectorX<>(builder.build()), toPVector());
    }
    public static <T> LazyPVectorX<T> PStack(Vector<T> q) {
        return fromPVector(new DexxVectorX<T>(q), toPVector());
    }
    private static <T> LazyPVectorX<T> fromPVector(PVector<T> vec, Reducer<PVector<T>> pVectorReducer) {
        return new LazyPVectorX<T>(vec,null, pVectorReducer);
    }
    @SafeVarargs
    public static <T> LazyPVectorX<T> PVector(T... elements){
        return fromPVector(of(elements),toPVector());
    }
    @Wither
    private final Vector<T> vector;

    public DexxVectorX<T> tail(){
        return withVector(vector.tail());
    }
    public T head(){
        return vector.get(0);
    }

    @Override
    public DexxVectorX<T> plus(T e) {
        return withVector(vector.append(e));
    }

    @Override
    public DexxVectorX<T> plusAll(Collection<? extends T> list) {
        Vector<T> vec = vector;
        for(T next :  list){
            vec = vec.append(next);
        }
        return withVector(vec);
     }
 
    private PVector<T> plusAllVec(Vector<? extends T> list) {
        Vector<T> vec = vector;
        for(T next :  list){
            vec = vec.append(next);
        }
        return withVector(vec);
     }

    @Override
    public DexxVectorX<T> with(int i, T e) {
        return withVector(vector.set(i,e));
    }

    @Override
    public PVector<T> plus(int i, T e) {
        if(i<0 || i>size())
            throw new IndexOutOfBoundsException("Index " + i + " is out of bounds - size : " + size());
        if(i==0)
            return withVector(vector.prepend(e));
        if(i==size()-1)
            return withVector(vector.append(e));
        
        return withVector(vector.take(i)).plus(e).plusAllVec(vector.drop(i));
       
    }

    @Override
    public PVector<T> plusAll(int i, Collection<? extends T> list) {
        return withVector(vector.take(i)).plusAll(list).plusAllVec(vector.drop(i));
    }

    @Override
    public PVector<T> minus(Object e) {
        return fromPVector(this,toPVector()).filter(i->!Objects.equals(i,e));
    }

    @Override
    public PVector<T> minusAll(Collection<?> list) {
        return (PVector<T>)fromPVector(this,toPVector()).removeAllI((Iterable<T>)list);
    }

    @Override
    public DexxVectorX<T> minus(int i) {
        if(i<0 || i>size())
            throw new IndexOutOfBoundsException("Index " + i + " is out of bounds - size : " + size());
        if(i==0)
            return withVector(vector.drop(1));
        
        return withVector(vector.take(i)).plusAll(withVector(vector.drop(i+1)));
    }

    @Override
    public DexxVectorX<T> subList(int start, int end) {
        return withVector(vector.drop(start).take(end-start));
    }

    @Override
    public T get(int index) {
        return vector.get(index);
    }

    @Override
    public int size() {
        return vector.size();
    }

   
}
