package cyclops.companion.guava;

import cyclops.monads.GuavaWitness.fluentIterable;
import com.aol.cyclops.guava.hkt.FluentIterableKind;
import com.aol.cyclops2.hkt.Higher;
import com.aol.cyclops2.types.anyM.AnyMSeq;
import com.google.common.collect.FluentIterable;
import cyclops.function.Fn3;
import cyclops.function.Fn4;
import cyclops.function.Monoid;
import cyclops.monads.AnyM;
import cyclops.stream.ReactiveSeq;
import cyclops.typeclasses.Pure;
import cyclops.typeclasses.foldable.Foldable;
import cyclops.typeclasses.functor.Functor;
import cyclops.typeclasses.instances.General;
import cyclops.typeclasses.monad.*;
import lombok.experimental.UtilityClass;

import java.util.function.*;

/**
 * Created by johnmcclean on 26/04/2017.
 */
public class FluentIterables {

    /**
     * <pre>
     * {@code
     * ToCyclopsReact.anyM(FluentIterable.of(new String[]{"hello world"}))
    .transform(String::toUpperCase)
    .transformAndConcat(i->AnyMonads.anyM(java.util.stream.Stream.of(i)))
    .toSequence()
    .toList()
     * }
     *  //[HELLO WORLD]
     * </pre>
     *
     * @param streamM to construct AnyM from
     * @return AnyM
     */
    public static <T> AnyMSeq<fluentIterable,T> anyM(FluentIterable<T> streamM) {
        return AnyM.ofSeq(streamM, fluentIterable.INSTANCE);
    }

    /**
     * Perform a For Comprehension over a FluentIterable, accepting 3 generating functions.
     * This results in a four level nested internal iteration over the provided Publishers.
     *
     *  <pre>
     * {@code
     *
     *   import static cyclops.FluentIterables.forEach4;
     *
    forEach4(IntFluentIterable.range(1,10).boxed(),
    a-> FluentIterable.iterate(a,i->i+1).limit(10),
    (a,b) -> FluentIterable.<Integer>of(a+b),
    (a,b,c) -> FluentIterable.<Integer>just(a+b+c),
    Tuple::tuple)
     *
     * }
     * </pre>
     *
     * @param value1 top level FluentIterable
     * @param value2 Nested FluentIterable
     * @param value3 Nested FluentIterable
     * @param value4 Nested FluentIterable
     * @param yieldingFunction  Generates a result per combination
     * @return FluentIterable with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, T3, R1, R2, R3, R> FluentIterable<R> forEach4(FluentIterable<? extends T1> value1,
                                                                         Function<? super T1, ? extends FluentIterable<R1>> value2,
                                                                         BiFunction<? super T1, ? super R1, ? extends FluentIterable<R2>> value3,
                                                                         Fn3<? super T1, ? super R1, ? super R2, ? extends FluentIterable<R3>> value4,
                                                                         Fn4<? super T1, ? super R1, ? super R2, ? super R3, ? extends R> yieldingFunction) {


        return value1.transformAndConcat(in -> {

            FluentIterable<R1> a = value2.apply(in);
            return a.transformAndConcat(ina -> {
                FluentIterable<R2> b = value3.apply(in,ina);
                return b.transformAndConcat(inb -> {
                    FluentIterable<R3> c = value4.apply(in,ina,inb);
                    return c.transform(in2 -> yieldingFunction.apply(in, ina, inb, in2));
                });

            });

        });

    }

    /**
     * Perform a For Comprehension over a FluentIterable, accepting 3 generating function.
     * This results in a four level nested internal iteration over the provided Publishers.
     * <pre>
     * {@code
     *
     *  import static com.aol.cyclops2.reactor.FluentIterablees.forEach4;
     *
     *  forEach4(IntFluentIterable.range(1,10).boxed(),
    a-> FluentIterable.iterate(a,i->i+1).limit(10),
    (a,b) -> FluentIterable.<Integer>just(a+b),
    (a,b,c) -> FluentIterable.<Integer>just(a+b+c),
    (a,b,c,d) -> a+b+c+d <100,
    Tuple::tuple);
     *
     * }
     * </pre>
     *
     * @param value1 top level FluentIterable
     * @param value2 Nested FluentIterable
     * @param value3 Nested FluentIterable
     * @param value4 Nested FluentIterable
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return FluentIterable with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, T3, R1, R2, R3, R> FluentIterable<R> forEach4(FluentIterable<? extends T1> value1,
                                                                         Function<? super T1, ? extends FluentIterable<R1>> value2,
                                                                         BiFunction<? super T1, ? super R1, ? extends FluentIterable<R2>> value3,
                                                                         Fn3<? super T1, ? super R1, ? super R2, ? extends FluentIterable<R3>> value4,
                                                                         Fn4<? super T1, ? super R1, ? super R2, ? super R3, Boolean> filterFunction,
                                                                         Fn4<? super T1, ? super R1, ? super R2, ? super R3, ? extends R> yieldingFunction) {


        return value1.transformAndConcat(in -> {

            FluentIterable<R1> a = value2.apply(in);
            return a.transformAndConcat(ina -> {
                FluentIterable<R2> b = value3.apply(in,ina);
                return b.transformAndConcat(inb -> {
                    FluentIterable<R3> c = value4.apply(in,ina,inb);
                    return c.filter(in2->filterFunction.apply(in,ina,inb,in2))
                            .transform(in2 -> yieldingFunction.apply(in, ina, inb, in2));
                });

            });

        });
    }

    /**
     * Perform a For Comprehension over a FluentIterable, accepting 2 generating function.
     * This results in a three level nested internal iteration over the provided Publishers.
     *
     * <pre>
     * {@code
     *
     * import static FluentIterables.forEach3;
     *
     * forEach(IntFluentIterable.range(1,10).boxed(),
    a-> FluentIterable.iterate(a,i->i+1).limit(10),
    (a,b) -> FluentIterable.<Integer>of(a+b),
    Tuple::tuple);
     *
     * }
     * </pre>
     *
     *
     * @param value1 top level FluentIterable
     * @param value2 Nested FluentIterable
     * @param value3 Nested FluentIterable
     * @param yieldingFunction Generates a result per combination
     * @return FluentIterable with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, R1, R2, R> FluentIterable<R> forEach3(FluentIterable<? extends T1> value1,
                                                                 Function<? super T1, ? extends FluentIterable<R1>> value2,
                                                                 BiFunction<? super T1, ? super R1, ? extends FluentIterable<R2>> value3,
                                                                 Fn3<? super T1, ? super R1, ? super R2, ? extends R> yieldingFunction) {

        return value1.transformAndConcat(in -> {

            FluentIterable<R1> a = value2.apply(in);
            return a.transformAndConcat(ina -> {
                FluentIterable<R2> b = value3.apply(in,ina);
                return b.transform(in2 -> yieldingFunction.apply(in, ina, in2));
            });


        });


    }

    /**
     * Perform a For Comprehension over a FluentIterable, accepting 2 generating function.
     * This results in a three level nested internal iteration over the provided Publishers.
     * <pre>
     * {@code
     *
     * import static FluentIterables.forEach;
     *
     * forEach(IntFluentIterable.range(1,10).boxed(),
    a-> FluentIterable.iterate(a,i->i+1).limit(10),
    (a,b) -> FluentIterable.<Integer>of(a+b),
    (a,b,c) ->a+b+c<10,
    Tuple::tuple)
    .toFluentIterableX();
     * }
     * </pre>
     *
     * @param value1 top level FluentIterable
     * @param value2 Nested publisher
     * @param value3 Nested publisher
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T1, T2, R1, R2, R> FluentIterable<R> forEach3(FluentIterable<? extends T1> value1,
                                                                 Function<? super T1, ? extends FluentIterable<R1>> value2,
                                                                 BiFunction<? super T1, ? super R1, ? extends FluentIterable<R2>> value3,
                                                                 Fn3<? super T1, ? super R1, ? super R2, Boolean> filterFunction,
                                                                 Fn3<? super T1, ? super R1, ? super R2, ? extends R> yieldingFunction) {


        return value1.transformAndConcat(in -> {

            FluentIterable<R1> a = value2.apply(in);
            return a.transformAndConcat(ina -> {
                FluentIterable<R2> b = value3.apply(in,ina);
                return b.filter(in2->filterFunction.apply(in,ina,in2))
                        .transform(in2 -> yieldingFunction.apply(in, ina, in2));
            });



        });
    }

    /**
     * Perform a For Comprehension over a FluentIterable, accepting an additonal generating function.
     * This results in a two level nested internal iteration over the provided Publishers.
     *
     * <pre>
     * {@code
     *
     *  import static FluentIterables.forEach2;
     *  forEach(IntFluentIterable.range(1, 10).boxed(),
     *          i -> FluentIterable.range(i, 10), Tuple::tuple)
    .forEach(System.out::println);

    //(1, 1)
    (1, 2)
    (1, 3)
    (1, 4)
    ...
     *
     * }</pre>
     *
     * @param value1 top level FluentIterable
     * @param value2 Nested publisher
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T, R1, R> FluentIterable<R> forEach2(FluentIterable<? extends T> value1,
                                                        Function<? super T, FluentIterable<R1>> value2,
                                                        BiFunction<? super T, ? super R1, ? extends R> yieldingFunction) {


        return value1.transformAndConcat(in -> {

            FluentIterable<R1> a = value2.apply(in);
            return a.transform(in2 -> yieldingFunction.apply(in,  in2));
        });

    }

    /**
     *
     * <pre>
     * {@code
     *
     *   import static FluentIterables.forEach2;
     *
     *   forEach(IntFluentIterable.range(1, 10).boxed(),
     *           i -> FluentIterable.range(i, 10),
     *           (a,b) -> a>2 && b<10,
     *           Tuple::tuple)
    .forEach(System.out::println);

    //(3, 3)
    (3, 4)
    (3, 5)
    (3, 6)
    (3, 7)
    (3, 8)
    (3, 9)
    ...

     *
     * }</pre>
     *
     *
     * @param value1 top level FluentIterable
     * @param value2 Nested publisher
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T, R1, R> FluentIterable<R> forEach2(FluentIterable<? extends T> value1,
                                                        Function<? super T, ? extends FluentIterable<R1>> value2,
                                                        BiFunction<? super T, ? super R1, Boolean> filterFunction,
                                                        BiFunction<? super T, ? super R1, ? extends R> yieldingFunction) {


        return value1.transformAndConcat(in -> {

            FluentIterable<R1> a = value2.apply(in);
            return a.filter(in2->filterFunction.apply(in,in2))
                    .transform(in2 -> yieldingFunction.apply(in,  in2));
        });
    }
    /**
     * Companion class for creating Type Class instances for working with FluentIterables
     * @author johnmcclean
     *
     */
    @UtilityClass
    public class Instances {


        /**
         *
         * Transform a flux, mulitplying every element by 2
         *
         * <pre>
         * {@code
         *  FluentIterableKind<Integer> flux = FluentIterables.functor().transform(i->i*2, FluentIterableKind.widen(FluentIterable.of(1,2,3));
         *
         *  //[2,4,6]
         *
         *
         * }
         * </pre>
         *
         * An example fluent api working with FluentIterables
         * <pre>
         * {@code
         *   FluentIterableKind<Integer> flux = FluentIterables.unit()
        .unit("hello")
        .then(h->FluentIterables.functor().transform((String v) ->v.length(), h))
        .convert(FluentIterableKind::narrowK);
         *
         * }
         * </pre>
         *
         *
         * @return A functor for FluentIterables
         */
        public static <T,R>Functor<FluentIterableKind.µ> functor(){
            BiFunction<FluentIterableKind<T>,Function<? super T, ? extends R>,FluentIterableKind<R>> transform = Instances::transform;
            return General.functor(transform);
        }
        /**
         * <pre>
         * {@code
         * FluentIterableKind<String> flux = FluentIterables.unit()
        .unit("hello")
        .convert(FluentIterableKind::narrowK);

        //FluentIterable.of("hello"))
         *
         * }
         * </pre>
         *
         *
         * @return A factory for FluentIterables
         */
        public static <T> Pure<FluentIterableKind.µ> unit(){
            return General.<FluentIterableKind.µ,T>unit(Instances::of);
        }
        /**
         *
         * <pre>
         * {@code
         * import static com.aol.cyclops.hkt.jdk.FluentIterableKind.widen;
         * import static com.aol.cyclops.util.function.Lambda.l1;
         *
        FluentIterables.zippingApplicative()
        .ap(widen(FluentIterable.of(l1(this::multiplyByTwo))),widen(FluentIterable.of(1,2,3)));
         *
         * //[2,4,6]
         * }
         * </pre>
         *
         *
         * Example fluent API
         * <pre>
         * {@code
         * FluentIterableKind<Function<Integer,Integer>> fluxFn =FluentIterables.unit()
         *                                                  .unit(Lambda.l1((Integer i) ->i*2))
         *                                                  .convert(FluentIterableKind::narrowK);

        FluentIterableKind<Integer> flux = FluentIterables.unit()
        .unit("hello")
        .then(h->FluentIterables.functor().transform((String v) ->v.length(), h))
        .then(h->FluentIterables.zippingApplicative().ap(fluxFn, h))
        .convert(FluentIterableKind::narrowK);

        //FluentIterable.of("hello".length()*2))
         *
         * }
         * </pre>
         *
         *
         * @return A zipper for FluentIterables
         */
        public static <T,R> Applicative<FluentIterableKind.µ> zippingApplicative(){
            BiFunction<FluentIterableKind< Function<T, R>>,FluentIterableKind<T>,FluentIterableKind<R>> ap = Instances::ap;
            return General.applicative(functor(), unit(), ap);
        }
        /**
         *
         * <pre>
         * {@code
         * import static com.aol.cyclops.hkt.jdk.FluentIterableKind.widen;
         * FluentIterableKind<Integer> flux  = FluentIterables.monad()
        .transformAndConcat(i->widen(FluentIterableX.range(0,i)), widen(FluentIterable.of(1,2,3)))
        .convert(FluentIterableKind::narrowK);
         * }
         * </pre>
         *
         * Example fluent API
         * <pre>
         * {@code
         *    FluentIterableKind<Integer> flux = FluentIterables.unit()
        .unit("hello")
        .then(h->FluentIterables.monad().transformAndConcat((String v) ->FluentIterables.unit().unit(v.length()), h))
        .convert(FluentIterableKind::narrowK);

        //FluentIterable.of("hello".length())
         *
         * }
         * </pre>
         *
         * @return Type class with monad functions for FluentIterables
         */
        public static <T,R> Monad<FluentIterableKind.µ> monad(){

            BiFunction<Higher<FluentIterableKind.µ,T>,Function<? super T, ? extends Higher<FluentIterableKind.µ,R>>,Higher<FluentIterableKind.µ,R>> transformAndConcat = Instances::transformAndConcat;
            return General.monad(zippingApplicative(), transformAndConcat);
        }
        /**
         *
         * <pre>
         * {@code
         *  FluentIterableKind<String> flux = FluentIterables.unit()
        .unit("hello")
        .then(h->FluentIterables.monadZero().filter((String t)->t.startsWith("he"), h))
        .convert(FluentIterableKind::narrowK);

        //FluentIterable.of("hello"));
         *
         * }
         * </pre>
         *
         *
         * @return A filterable monad (with default value)
         */
        public static <T,R> MonadZero<FluentIterableKind.µ> monadZero(){
            BiFunction<Higher<FluentIterableKind.µ,T>,Predicate<? super T>,Higher<FluentIterableKind.µ,T>> filter = Instances::filter;
            Supplier<Higher<FluentIterableKind.µ, T>> zero = ()-> FluentIterableKind.widen(FluentIterable.of());
            return General.<FluentIterableKind.µ,T,R>monadZero(monad(), zero,filter);
        }
        /**
         * <pre>
         * {@code
         *  FluentIterableKind<Integer> flux = FluentIterables.<Integer>monadPlus()
        .plus(FluentIterableKind.widen(FluentIterable.of()), FluentIterableKind.widen(FluentIterable.of(10)))
        .convert(FluentIterableKind::narrowK);
        //FluentIterable.of(10))
         *
         * }
         * </pre>
         * @return Type class for combining FluentIterables by concatenation
         */
        public static <T> MonadPlus<FluentIterableKind.µ> monadPlus(){
            Monoid<FluentIterableKind<T>> m = Monoid.of(FluentIterableKind.widen(FluentIterable.<T>of()), Instances::concat);
            Monoid<Higher<FluentIterableKind.µ,T>> m2= (Monoid)m;
            return General.monadPlus(monadZero(),m2);
        }
        /**
         *
         * <pre>
         * {@code
         *  Monoid<FluentIterableKind<Integer>> m = Monoid.of(FluentIterableKind.widen(FluentIterable.of()), (a,b)->a.isEmpty() ? b : a);
        FluentIterableKind<Integer> flux = FluentIterables.<Integer>monadPlus(m)
        .plus(FluentIterableKind.widen(FluentIterable.of(5)), FluentIterableKind.widen(FluentIterable.of(10)))
        .convert(FluentIterableKind::narrowK);
        //FluentIterable.of(5))
         *
         * }
         * </pre>
         *
         * @param m Monoid to use for combining FluentIterables
         * @return Type class for combining FluentIterables
         */
        public static <T> MonadPlus<FluentIterableKind.µ> monadPlus(Monoid<FluentIterableKind<T>> m){
            Monoid<Higher<FluentIterableKind.µ,T>> m2= (Monoid)m;
            return General.monadPlus(monadZero(),m2);
        }

        /**
         * @return Type class for traversables with traverse / sequence operations
         */
        public static <C2,T> Traverse<FluentIterableKind.µ> traverse(){
            BiFunction<Applicative<C2>,FluentIterableKind<Higher<C2, T>>,Higher<C2, FluentIterableKind<T>>> sequenceFn = (ap, flux) -> {

                Higher<C2,FluentIterableKind<T>> identity = ap.unit(FluentIterableKind.widen(FluentIterable.of()));

                BiFunction<Higher<C2,FluentIterableKind<T>>,Higher<C2,T>,Higher<C2,FluentIterableKind<T>>> combineToFluentIterable =   (acc, next) -> ap.apBiFn(ap.unit((a, b) -> FluentIterableKind.widen(FluentIterable.concat(a,FluentIterable.of(b)))),acc,next);

                BinaryOperator<Higher<C2,FluentIterableKind<T>>> combineFluentIterables = (a, b)-> ap.apBiFn(ap.unit((l1, l2)-> { return FluentIterableKind.widen(FluentIterable.concat(l1.narrow(),l2.narrow()));}),a,b); ;

                return ReactiveSeq.fromIterable(flux).reduce(identity,
                        combineToFluentIterable,
                        combineFluentIterables);


            };
            BiFunction<Applicative<C2>,Higher<FluentIterableKind.µ,Higher<C2, T>>,Higher<C2, Higher<FluentIterableKind.µ,T>>> sequenceNarrow  =
                    (a,b) -> FluentIterableKind.widen2(sequenceFn.apply(a, FluentIterableKind.narrowK(b)));
            return General.traverse(zippingApplicative(), sequenceNarrow);
        }

        /**
         *
         * <pre>
         * {@code
         * int sum  = FluentIterables.foldable()
        .foldLeft(0, (a,b)->a+b, FluentIterableKind.widen(FluentIterable.of(1,2,3,4)));

        //10
         *
         * }
         * </pre>
         *
         *
         * @return Type class for folding / reduction operations
         */
        public static <T> Foldable<FluentIterableKind.µ> foldable(){
            BiFunction<Monoid<T>,Higher<FluentIterableKind.µ,T>,T> foldRightFn =  (m, l)-> ReactiveSeq.fromPublisher(FluentIterableKind.narrowK(l)).foldRight(m);
            BiFunction<Monoid<T>,Higher<FluentIterableKind.µ,T>,T> foldLeftFn = (m, l)-> ReactiveSeq.fromPublisher(FluentIterableKind.narrowK(l)).reduce(m);
            return General.foldable(foldRightFn, foldLeftFn);
        }

        private static  <T> FluentIterableKind<T> concat(FluentIterableKind<T> l1, FluentIterableKind<T> l2){
            return FluentIterableKind.widen(FluentIterable.concat(l1,l2));
        }
        private <T> FluentIterableKind<T> of(T value){
            return FluentIterableKind.widen(FluentIterable.of(value));
        }
        private static <T,R> FluentIterableKind<R> ap(FluentIterableKind<Function< T, R>> lt, FluentIterableKind<T> flux){
            return FluentIterableKind.widen(lt.toReactiveSeq().zip(flux,(a, b)->a.apply(b)));
        }
        private static <T,R> Higher<FluentIterableKind.µ,R> transformAndConcat(Higher<FluentIterableKind.µ,T> lt, Function<? super T, ? extends  Higher<FluentIterableKind.µ,R>> fn){
            return FluentIterableKind.widen(FluentIterableKind.narrowK(lt).transformAndConcat(i->fn.andThen(FluentIterableKind::narrowK).apply(i)));
        }
        private static <T,R> FluentIterableKind<R> transform(FluentIterableKind<T> lt, Function<? super T, ? extends R> fn){
            return FluentIterableKind.widen(lt.transform(i->fn.apply(i)));
        }
        private static <T> FluentIterableKind<T> filter(Higher<FluentIterableKind.µ,T> lt, Predicate<? super T> fn){
            return FluentIterableKind.widen(FluentIterableKind.narrow(lt).filter(i->fn.test(i)));
        }
    }

}
