package cyclops.companion.vavr;

import com.oath.cyclops.anym.AnyMSeq;
import cyclops.control.Either;
import cyclops.function.Function3;
import cyclops.function.Function4;
import cyclops.monads.AnyM;
import cyclops.monads.VavrWitness.hashSet;
import cyclops.monads.WitnessType;
import cyclops.monads.XorM;
import io.vavr.collection.HashSet;
import io.vavr.collection.Set;

import java.util.function.BiFunction;
import java.util.function.Function;




public class HashSets {


    public static  <W1 extends WitnessType<W1>,T> XorM<W1,hashSet,T> xorM(HashSet<T> type){
        return XorM.right(anyM(type));
    }
    public static  <W1 extends WitnessType<W1>,T> XorM<W1,hashSet,T> xorM(T... values){
        return xorM(HashSet.of(values));
    }
    public static <T> AnyMSeq<hashSet,T> anyM(HashSet<T> option) {
        return AnyM.ofSeq(option, hashSet.INSTANCE);
    }

    public static  <T,R> HashSet<R> tailRec(T initial, Function<? super T, ? extends HashSet<? extends io.vavr.control.Either<T, R>>> fn) {
        HashSet<io.vavr.control.Either<T, R>> next = HashSet.of(io.vavr.control.Either.left(initial));

        boolean newValue[] = {true};
        for(;;){

            next = next.flatMap(e -> e.fold(s -> {
                        newValue[0]=true;
                        return fn.apply(s); },
                    p -> {
                        newValue[0]=false;
                        return HashSet.of(e);
                    }));
            if(!newValue[0])
                break;

        }

        return next.filter(io.vavr.control.Either::isRight).map(io.vavr.control.Either::get);
    }
    public static  <T,R> HashSet<R> tailRecEither(T initial, Function<? super T, ? extends HashSet<? extends Either<T, R>>> fn) {
        HashSet<Either<T, R>> next = HashSet.of(Either.left(initial));

        boolean newValue[] = {true};
        for(;;){

            next = next.flatMap(e -> e.visit(s -> {
                        newValue[0]=true;
                        return fn.apply(s); },
                    p -> {
                        newValue[0]=false;
                        return HashSet.of(e);
                    }));
            if(!newValue[0])
                break;

        }

        return next.filter(Either::isRight).map(e->e.orElse(null));
    }


    /**
     * Perform a For Comprehension over a Set, accepting 3 generating functions.
     * This results in a four level nested internal iteration over the provided Publishers.
     *
     *  <pre>
     * {@code
     *
     *   import static cyclops.HashSets.forEach4;
     *
    forEach4(IntSet.range(1,10).boxed(),
    a-> Set.iterate(a,i->i+1).limit(10),
    (a,b) -> Set.<Integer>of(a+b),
    (a,b,c) -> Set.<Integer>just(a+b+c),
    Tuple::tuple)
     *
     * }
     * </pre>
     *
     * @param value1 top level Set
     * @param value2 Nested Set
     * @param value3 Nested Set
     * @param value4 Nested Set
     * @param yieldingFunction  Generates a result per combination
     * @return Set with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, T3, R1, R2, R3, R> Set<R> forEach4(Set<? extends T1> value1,
                                                               Function<? super T1, ? extends Set<R1>> value2,
                                                               BiFunction<? super T1, ? super R1, ? extends Set<R2>> value3,
                                                               Function3<? super T1, ? super R1, ? super R2, ? extends Set<R3>> value4,
                                                               Function4<? super T1, ? super R1, ? super R2, ? super R3, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Set<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Set<R2> b = value3.apply(in,ina);
                return b.flatMap(inb -> {
                    Set<R3> c = value4.apply(in,ina,inb);
                    return c.map(in2 -> yieldingFunction.apply(in, ina, inb, in2));
                });

            });

        });

    }

    /**
     * Perform a For Comprehension over a Set, accepting 3 generating function.
     * This results in a four level nested internal iteration over the provided Publishers.
     * <pre>
     * {@code
     *
     *  import static com.oath.cyclops.reactor.Setes.forEach4;
     *
     *  forEach4(IntSet.range(1,10).boxed(),
    a-> Set.iterate(a,i->i+1).limit(10),
    (a,b) -> Set.<Integer>just(a+b),
    (a,b,c) -> Set.<Integer>just(a+b+c),
    (a,b,c,d) -> a+b+c+d <100,
    Tuple::tuple);
     *
     * }
     * </pre>
     *
     * @param value1 top level Set
     * @param value2 Nested Set
     * @param value3 Nested Set
     * @param value4 Nested Set
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return Set with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, T3, R1, R2, R3, R> Set<R> forEach4(Set<? extends T1> value1,
                                                                 Function<? super T1, ? extends Set<R1>> value2,
                                                                 BiFunction<? super T1, ? super R1, ? extends Set<R2>> value3,
                                                                 Function3<? super T1, ? super R1, ? super R2, ? extends Set<R3>> value4,
                                                                 Function4<? super T1, ? super R1, ? super R2, ? super R3, Boolean> filterFunction,
                                                                 Function4<? super T1, ? super R1, ? super R2, ? super R3, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Set<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Set<R2> b = value3.apply(in,ina);
                return b.flatMap(inb -> {
                    Set<R3> c = value4.apply(in,ina,inb);
                    return c.filter(in2->filterFunction.apply(in,ina,inb,in2))
                            .map(in2 -> yieldingFunction.apply(in, ina, inb, in2));
                });

            });

        });
    }

    /**
     * Perform a For Comprehension over a Set, accepting 2 generating function.
     * This results in a three level nested internal iteration over the provided Publishers.
     *
     * <pre>
     * {@code
     *
     * import static HashSets.forEach3;
     *
     * forEach(IntSet.range(1,10).boxed(),
    a-> Set.iterate(a,i->i+1).limit(10),
    (a,b) -> Set.<Integer>of(a+b),
    Tuple::tuple);
     *
     * }
     * </pre>
     *
     *
     * @param value1 top level Set
     * @param value2 Nested Set
     * @param value3 Nested Set
     * @param yieldingFunction Generates a result per combination
     * @return Set with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, R1, R2, R> Set<R> forEach3(Set<? extends T1> value1,
                                                         Function<? super T1, ? extends Set<R1>> value2,
                                                         BiFunction<? super T1, ? super R1, ? extends Set<R2>> value3,
                                                         Function3<? super T1, ? super R1, ? super R2, ? extends R> yieldingFunction) {

        return value1.flatMap(in -> {

            Set<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Set<R2> b = value3.apply(in,ina);
                return b.map(in2 -> yieldingFunction.apply(in, ina, in2));
            });


        });


    }

    /**
     * Perform a For Comprehension over a Set, accepting 2 generating function.
     * This results in a three level nested internal iteration over the provided Publishers.
     * <pre>
     * {@code
     *
     * import static HashSets.forEach;
     *
     * forEach(IntSet.range(1,10).boxed(),
    a-> Set.iterate(a,i->i+1).limit(10),
    (a,b) -> Set.<Integer>of(a+b),
    (a,b,c) ->a+b+c<10,
    Tuple::tuple)
    .toSetX();
     * }
     * </pre>
     *
     * @param value1 top level Set
     * @param value2 Nested publisher
     * @param value3 Nested publisher
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T1, T2, R1, R2, R> Set<R> forEach3(Set<? extends T1> value1,
                                                         Function<? super T1, ? extends Set<R1>> value2,
                                                         BiFunction<? super T1, ? super R1, ? extends Set<R2>> value3,
                                                         Function3<? super T1, ? super R1, ? super R2, Boolean> filterFunction,
                                                         Function3<? super T1, ? super R1, ? super R2, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Set<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Set<R2> b = value3.apply(in,ina);
                return b.filter(in2->filterFunction.apply(in,ina,in2))
                        .map(in2 -> yieldingFunction.apply(in, ina, in2));
            });



        });
    }

    /**
     * Perform a For Comprehension over a Set, accepting an additonal generating function.
     * This results in a two level nested internal iteration over the provided Publishers.
     *
     * <pre>
     * {@code
     *
     *  import static HashSets.forEach2;
     *  forEach(IntSet.range(1, 10).boxed(),
     *          i -> Set.range(i, 10), Tuple::tuple)
    .forEach(System.out::println);

    //(1, 1)
    (1, 2)
    (1, 3)
    (1, 4)
    ...
     *
     * }</pre>
     *
     * @param value1 top level Set
     * @param value2 Nested publisher
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T, R1, R> Set<R> forEach2(Set<? extends T> value1,
                                                Function<? super T, Set<R1>> value2,
                                                BiFunction<? super T, ? super R1, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Set<R1> a = value2.apply(in);
            return a.map(in2 -> yieldingFunction.apply(in,  in2));
        });

    }

    /**
     *
     * <pre>
     * {@code
     *
     *   import static HashSets.forEach2;
     *
     *   forEach(IntSet.range(1, 10).boxed(),
     *           i -> Set.range(i, 10),
     *           (a,b) -> a>2 && b<10,
     *           Tuple::tuple)
    .forEach(System.out::println);

    //(3, 3)
    (3, 4)
    (3, 5)
    (3, 6)
    (3, 7)
    (3, 8)
    (3, 9)
    ...

     *
     * }</pre>
     *
     *
     * @param value1 top level Set
     * @param value2 Nested publisher
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T, R1, R> Set<R> forEach2(Set<? extends T> value1,
                                                Function<? super T, ? extends Set<R1>> value2,
                                                BiFunction<? super T, ? super R1, Boolean> filterFunction,
                                                BiFunction<? super T, ? super R1, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Set<R1> a = value2.apply(in);
            return a.filter(in2->filterFunction.apply(in,in2))
                    .map(in2 -> yieldingFunction.apply(in,  in2));
        });
    }



}
