package cyclops.companion.vavr;

import cyclops.conversion.vavr.FromCyclopsReact;
import cyclops.monads.VavrWitness.queue;
import com.aol.cyclops.vavr.hkt.QueueKind;
import com.aol.cyclops2.hkt.Higher;
import com.aol.cyclops2.types.anyM.AnyMSeq;
import cyclops.function.Fn3;
import cyclops.function.Fn4;
import cyclops.function.Monoid;
import cyclops.monads.AnyM;
import cyclops.stream.ReactiveSeq;
import cyclops.typeclasses.Pure;
import cyclops.typeclasses.foldable.Foldable;
import cyclops.typeclasses.functor.Functor;
import cyclops.typeclasses.instances.General;
import cyclops.typeclasses.monad.*;
import javaslang.collection.Queue;
import lombok.experimental.UtilityClass;

import java.util.function.BiFunction;
import java.util.function.BinaryOperator;
import java.util.function.Function;


public class Queues {


   
    public static <T> AnyMSeq<queue,T> anyM(Queue<T> option) {
        return AnyM.ofSeq(option, queue.INSTANCE);
    }
    /**
     * Perform a For Comprehension over a Queue, accepting 3 generating functions.
     * This results in a four level nested internal iteration over the provided Publishers.
     *
     *  <pre>
     * {@code
     *
     *   import static cyclops.Queues.forEach4;
     *
    forEach4(IntQueue.range(1,10).boxed(),
    a-> Queue.iterate(a,i->i+1).limit(10),
    (a,b) -> Queue.<Integer>of(a+b),
    (a,b,c) -> Queue.<Integer>just(a+b+c),
    Tuple::tuple)
     *
     * }
     * </pre>
     *
     * @param value1 top level Queue
     * @param value2 Nested Queue
     * @param value3 Nested Queue
     * @param value4 Nested Queue
     * @param yieldingFunction  Generates a result per combination
     * @return Queue with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, T3, R1, R2, R3, R> Queue<R> forEach4(Queue<? extends T1> value1,
                                                               Function<? super T1, ? extends Queue<R1>> value2,
                                                               BiFunction<? super T1, ? super R1, ? extends Queue<R2>> value3,
                                                               Fn3<? super T1, ? super R1, ? super R2, ? extends Queue<R3>> value4,
                                                               Fn4<? super T1, ? super R1, ? super R2, ? super R3, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Queue<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Queue<R2> b = value3.apply(in,ina);
                return b.flatMap(inb -> {
                    Queue<R3> c = value4.apply(in,ina,inb);
                    return c.map(in2 -> yieldingFunction.apply(in, ina, inb, in2));
                });

            });

        });

    }

    /**
     * Perform a For Comprehension over a Queue, accepting 3 generating function.
     * This results in a four level nested internal iteration over the provided Publishers.
     * <pre>
     * {@code
     *
     *  import static com.aol.cyclops2.reactor.Queuees.forEach4;
     *
     *  forEach4(IntQueue.range(1,10).boxed(),
    a-> Queue.iterate(a,i->i+1).limit(10),
    (a,b) -> Queue.<Integer>just(a+b),
    (a,b,c) -> Queue.<Integer>just(a+b+c),
    (a,b,c,d) -> a+b+c+d <100,
    Tuple::tuple);
     *
     * }
     * </pre>
     *
     * @param value1 top level Queue
     * @param value2 Nested Queue
     * @param value3 Nested Queue
     * @param value4 Nested Queue
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return Queue with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, T3, R1, R2, R3, R> Queue<R> forEach4(Queue<? extends T1> value1,
                                                                 Function<? super T1, ? extends Queue<R1>> value2,
                                                                 BiFunction<? super T1, ? super R1, ? extends Queue<R2>> value3,
                                                                 Fn3<? super T1, ? super R1, ? super R2, ? extends Queue<R3>> value4,
                                                                 Fn4<? super T1, ? super R1, ? super R2, ? super R3, Boolean> filterFunction,
                                                                 Fn4<? super T1, ? super R1, ? super R2, ? super R3, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Queue<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Queue<R2> b = value3.apply(in,ina);
                return b.flatMap(inb -> {
                    Queue<R3> c = value4.apply(in,ina,inb);
                    return c.filter(in2->filterFunction.apply(in,ina,inb,in2))
                            .map(in2 -> yieldingFunction.apply(in, ina, inb, in2));
                });

            });

        });
    }

    /**
     * Perform a For Comprehension over a Queue, accepting 2 generating function.
     * This results in a three level nested internal iteration over the provided Publishers.
     *
     * <pre>
     * {@code
     *
     * import static Queues.forEach3;
     *
     * forEach(IntQueue.range(1,10).boxed(),
    a-> Queue.iterate(a,i->i+1).limit(10),
    (a,b) -> Queue.<Integer>of(a+b),
    Tuple::tuple);
     *
     * }
     * </pre>
     *
     *
     * @param value1 top level Queue
     * @param value2 Nested Queue
     * @param value3 Nested Queue
     * @param yieldingFunction Generates a result per combination
     * @return Queue with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, R1, R2, R> Queue<R> forEach3(Queue<? extends T1> value1,
                                                         Function<? super T1, ? extends Queue<R1>> value2,
                                                         BiFunction<? super T1, ? super R1, ? extends Queue<R2>> value3,
                                                         Fn3<? super T1, ? super R1, ? super R2, ? extends R> yieldingFunction) {

        return value1.flatMap(in -> {

            Queue<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Queue<R2> b = value3.apply(in,ina);
                return b.map(in2 -> yieldingFunction.apply(in, ina, in2));
            });


        });


    }

    /**
     * Perform a For Comprehension over a Queue, accepting 2 generating function.
     * This results in a three level nested internal iteration over the provided Publishers.
     * <pre>
     * {@code
     *
     * import static Queues.forEach;
     *
     * forEach(IntQueue.range(1,10).boxed(),
    a-> Queue.iterate(a,i->i+1).limit(10),
    (a,b) -> Queue.<Integer>of(a+b),
    (a,b,c) ->a+b+c<10,
    Tuple::tuple)
    .toQueueX();
     * }
     * </pre>
     *
     * @param value1 top level Queue
     * @param value2 Nested publisher
     * @param value3 Nested publisher
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T1, T2, R1, R2, R> Queue<R> forEach3(Queue<? extends T1> value1,
                                                         Function<? super T1, ? extends Queue<R1>> value2,
                                                         BiFunction<? super T1, ? super R1, ? extends Queue<R2>> value3,
                                                         Fn3<? super T1, ? super R1, ? super R2, Boolean> filterFunction,
                                                         Fn3<? super T1, ? super R1, ? super R2, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Queue<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Queue<R2> b = value3.apply(in,ina);
                return b.filter(in2->filterFunction.apply(in,ina,in2))
                        .map(in2 -> yieldingFunction.apply(in, ina, in2));
            });



        });
    }

    /**
     * Perform a For Comprehension over a Queue, accepting an additonal generating function.
     * This results in a two level nested internal iteration over the provided Publishers.
     *
     * <pre>
     * {@code
     *
     *  import static Queues.forEach2;
     *  forEach(IntQueue.range(1, 10).boxed(),
     *          i -> Queue.range(i, 10), Tuple::tuple)
    .forEach(System.out::println);

    //(1, 1)
    (1, 2)
    (1, 3)
    (1, 4)
    ...
     *
     * }</pre>
     *
     * @param value1 top level Queue
     * @param value2 Nested publisher
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T, R1, R> Queue<R> forEach2(Queue<? extends T> value1,
                                                Function<? super T, Queue<R1>> value2,
                                                BiFunction<? super T, ? super R1, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Queue<R1> a = value2.apply(in);
            return a.map(in2 -> yieldingFunction.apply(in,  in2));
        });

    }

    /**
     *
     * <pre>
     * {@code
     *
     *   import static Queues.forEach2;
     *
     *   forEach(IntQueue.range(1, 10).boxed(),
     *           i -> Queue.range(i, 10),
     *           (a,b) -> a>2 && b<10,
     *           Tuple::tuple)
    .forEach(System.out::println);

    //(3, 3)
    (3, 4)
    (3, 5)
    (3, 6)
    (3, 7)
    (3, 8)
    (3, 9)
    ...

     *
     * }</pre>
     *
     *
     * @param value1 top level Queue
     * @param value2 Nested publisher
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T, R1, R> Queue<R> forEach2(Queue<? extends T> value1,
                                                Function<? super T, ? extends Queue<R1>> value2,
                                                BiFunction<? super T, ? super R1, Boolean> filterFunction,
                                                BiFunction<? super T, ? super R1, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Queue<R1> a = value2.apply(in);
            return a.filter(in2->filterFunction.apply(in,in2))
                    .map(in2 -> yieldingFunction.apply(in,  in2));
        });
    }
    /**
     * Companion class for creating Type Class instances for working with Queues
     * @author johnmcclean
     *
     */
    @UtilityClass
    public static class Instances {


        /**
         *
         * Transform a list, mulitplying every element by 2
         *
         * <pre>
         * {@code
         *  QueueKind<Integer> list = Queues.functor().map(i->i*2, QueueKind.widen(Arrays.asQueue(1,2,3));
         *
         *  //[2,4,6]
         *
         *
         * }
         * </pre>
         *
         * An example fluent api working with Queues
         * <pre>
         * {@code
         *   QueueKind<Integer> list = Queues.unit()
        .unit("hello")
        .then(h->Queues.functor().map((String v) ->v.length(), h))
        .convert(QueueKind::narrowK);
         *
         * }
         * </pre>
         *
         *
         * @return A functor for Queues
         */
        public static <T,R>Functor<QueueKind.µ> functor(){
            BiFunction<QueueKind<T>,Function<? super T, ? extends R>,QueueKind<R>> map = Instances::map;
            return General.functor(map);
        }
        /**
         * <pre>
         * {@code
         * QueueKind<String> list = Queues.unit()
        .unit("hello")
        .convert(QueueKind::narrowK);

        //Arrays.asQueue("hello"))
         *
         * }
         * </pre>
         *
         *
         * @return A factory for Queues
         */
        public static <T> Pure<QueueKind.µ> unit(){
            return General.<QueueKind.µ,T>unit(QueueKind::of);
        }
        /**
         *
         * <pre>
         * {@code
         * import static com.aol.cyclops.hkt.jdk.QueueKind.widen;
         * import static com.aol.cyclops.util.function.Lambda.l1;
         * import static java.util.Arrays.asQueue;
         *
        Queues.zippingApplicative()
        .ap(widen(asQueue(l1(this::multiplyByTwo))),widen(asQueue(1,2,3)));
         *
         * //[2,4,6]
         * }
         * </pre>
         *
         *
         * Example fluent API
         * <pre>
         * {@code
         * QueueKind<Function<Integer,Integer>> listFn =Queues.unit()
         *                                                  .unit(Lambda.l1((Integer i) ->i*2))
         *                                                  .convert(QueueKind::narrowK);

        QueueKind<Integer> list = Queues.unit()
        .unit("hello")
        .then(h->Queues.functor().map((String v) ->v.length(), h))
        .then(h->Queues.zippingApplicative().ap(listFn, h))
        .convert(QueueKind::narrowK);

        //Arrays.asQueue("hello".length()*2))
         *
         * }
         * </pre>
         *
         *
         * @return A zipper for Queues
         */
        public static <T,R> Applicative<QueueKind.µ> zippingApplicative(){
            BiFunction<QueueKind< Function<T, R>>,QueueKind<T>,QueueKind<R>> ap = Instances::ap;
            return General.applicative(functor(), unit(), ap);
        }
        /**
         *
         * <pre>
         * {@code
         * import static com.aol.cyclops.hkt.jdk.QueueKind.widen;
         * QueueKind<Integer> list  = Queues.monad()
        .flatMap(i->widen(QueueX.range(0,i)), widen(Arrays.asQueue(1,2,3)))
        .convert(QueueKind::narrowK);
         * }
         * </pre>
         *
         * Example fluent API
         * <pre>
         * {@code
         *    QueueKind<Integer> list = Queues.unit()
        .unit("hello")
        .then(h->Queues.monad().flatMap((String v) ->Queues.unit().unit(v.length()), h))
        .convert(QueueKind::narrowK);

        //Arrays.asQueue("hello".length())
         *
         * }
         * </pre>
         *
         * @return Type class with monad functions for Queues
         */
        public static <T,R> Monad<QueueKind.µ> monad(){

            BiFunction<Higher<QueueKind.µ,T>,Function<? super T, ? extends Higher<QueueKind.µ,R>>,Higher<QueueKind.µ,R>> flatMap = Instances::flatMap;
            return General.monad(zippingApplicative(), flatMap);
        }
        /**
         *
         * <pre>
         * {@code
         *  QueueKind<String> list = Queues.unit()
        .unit("hello")
        .then(h->Queues.monadZero().filter((String t)->t.startsWith("he"), h))
        .convert(QueueKind::narrowK);

        //Arrays.asQueue("hello"));
         *
         * }
         * </pre>
         *
         *
         * @return A filterable monad (with default value)
         */
        public static <T,R> MonadZero<QueueKind.µ> monadZero(){

            return General.monadZero(monad(), QueueKind.widen(Queue.empty()));
        }
        /**
         * <pre>
         * {@code
         *  QueueKind<Integer> list = Queues.<Integer>monadPlus()
        .plus(QueueKind.widen(Arrays.asQueue()), QueueKind.widen(Arrays.asQueue(10)))
        .convert(QueueKind::narrowK);
        //Arrays.asQueue(10))
         *
         * }
         * </pre>
         * @return Type class for combining Queues by concatenation
         */
        public static <T> MonadPlus<QueueKind.µ> monadPlus(){
            Monoid<QueueKind<T>> m = Monoid.of(QueueKind.widen(Queue.empty()), Instances::concat);
            Monoid<Higher<QueueKind.µ,T>> m2= (Monoid)m;
            return General.monadPlus(monadZero(),m2);
        }
        /**
         *
         * <pre>
         * {@code
         *  Monoid<QueueKind<Integer>> m = Monoid.of(QueueKind.widen(Arrays.asQueue()), (a,b)->a.isEmpty() ? b : a);
        QueueKind<Integer> list = Queues.<Integer>monadPlus(m)
        .plus(QueueKind.widen(Arrays.asQueue(5)), QueueKind.widen(Arrays.asQueue(10)))
        .convert(QueueKind::narrowK);
        //Arrays.asQueue(5))
         *
         * }
         * </pre>
         *
         * @param m Monoid to use for combining Queues
         * @return Type class for combining Queues
         */
        public static <T> MonadPlus<QueueKind.µ> monadPlus(Monoid<QueueKind<T>> m){
            Monoid<Higher<QueueKind.µ,T>> m2= (Monoid)m;
            return General.monadPlus(monadZero(),m2);
        }

        /**
         * @return Type class for traversables with traverse / sequence operations
         */
        public static <C2,T> Traverse<QueueKind.µ> traverse(){

            BiFunction<Applicative<C2>,QueueKind<Higher<C2, T>>,Higher<C2, QueueKind<T>>> sequenceFn = (ap, list) -> {

                Higher<C2,QueueKind<T>> identity = ap.unit(QueueKind.widen(Queue.empty()));

                BiFunction<Higher<C2,QueueKind<T>>,Higher<C2,T>,Higher<C2,QueueKind<T>>> combineToQueue =   (acc, next) -> ap.apBiFn(ap.unit((a, b) -> QueueKind.widen(QueueKind.narrow(a).append(b))),
                        acc,next);

                BinaryOperator<Higher<C2,QueueKind<T>>> combineQueues = (a, b)-> ap.apBiFn(ap.unit((l1, l2)-> QueueKind.widen(QueueKind.narrow(l1).appendAll(l2))),a,b); ;

                return ReactiveSeq.fromIterable(QueueKind.narrow(list))
                        .reduce(identity,
                                combineToQueue,
                                combineQueues);


            };
            BiFunction<Applicative<C2>,Higher<QueueKind.µ,Higher<C2, T>>,Higher<C2, Higher<QueueKind.µ,T>>> sequenceNarrow  =
                    (a,b) -> QueueKind.widen2(sequenceFn.apply(a, QueueKind.narrowK(b)));
            return General.traverse(zippingApplicative(), sequenceNarrow);
        }

        /**
         *
         * <pre>
         * {@code
         * int sum  = Queues.foldable()
        .foldLeft(0, (a,b)->a+b, QueueKind.widen(Arrays.asQueue(1,2,3,4)));

        //10
         *
         * }
         * </pre>
         *
         *
         * @return Type class for folding / reduction operations
         */
        public static <T> Foldable<QueueKind.µ> foldable(){
            BiFunction<Monoid<T>,Higher<QueueKind.µ,T>,T> foldRightFn =  (m, l)-> ReactiveSeq.fromIterable(QueueKind.narrow(l)).foldRight(m);
            BiFunction<Monoid<T>,Higher<QueueKind.µ,T>,T> foldLeftFn = (m, l)-> ReactiveSeq.fromIterable(QueueKind.narrow(l)).reduce(m);
            return General.foldable(foldRightFn, foldLeftFn);
        }

        private static  <T> QueueKind<T> concat(QueueKind<T> l1, QueueKind<T> l2){

            return QueueKind.widen(l1.appendAll(QueueKind.narrow(l2)));

        }

        private static <T,R> QueueKind<R> ap(QueueKind<Function< T, R>> lt, QueueKind<T> list){
            return QueueKind.widen(FromCyclopsReact.fromStream(ReactiveSeq.fromIterable(lt).zip(list, (a, b)->a.apply(b))).toQueue());
        }
        private static <T,R> Higher<QueueKind.µ,R> flatMap(Higher<QueueKind.µ,T> lt, Function<? super T, ? extends  Higher<QueueKind.µ,R>> fn){
            return QueueKind.widen(QueueKind.narrow(lt).flatMap(fn.andThen(QueueKind::narrow)));
        }
        private static <T,R> QueueKind<R> map(QueueKind<T> lt, Function<? super T, ? extends R> fn){
            return QueueKind.widen(QueueKind.narrow(lt).map(in->fn.apply(in)));
        }
    }



}
