package cyclops.companion.vavr;

import com.oath.anym.AnyMSeq;
import cyclops.collections.vavr.VavrVectorX;
import cyclops.function.Function3;
import cyclops.function.Function4;
import cyclops.monads.AnyM;
import cyclops.monads.VavrWitness.vector;
import cyclops.monads.WitnessType;
import cyclops.monads.transformers.ListT;
import io.vavr.collection.Vector;

import java.util.function.BiFunction;
import java.util.function.Function;




public class Vectors {

    public static <T,W extends WitnessType<W>> ListT<W, T> liftM(Vector<T> opt, W witness) {
        return ListT.of(witness.adapter().unit(VavrVectorX.ofAll(opt)));
    }

    public static <T> AnyMSeq<vector,T> anyM(Vector<T> option) {
        return AnyM.ofSeq(option, vector.INSTANCE);
    }

    public static  <T,R> Vector<R> tailRec(T initial, Function<? super T, ? extends Vector<? extends io.vavr.control.Either<T, R>>> fn) {
        Vector<io.vavr.control.Either<T, R>> next = Vector.of(io.vavr.control.Either.left(initial));

        boolean newValue[] = {true};
        for(;;){

            next = next.flatMap(e -> e.fold(s -> {
                        newValue[0]=true;
                        return fn.apply(s); },
                    p -> {
                        newValue[0]=false;
                        return Vector.of(e);
                    }));
            if(!newValue[0])
                break;

        }

        return next.filter(io.vavr.control.Either::isRight).map(io.vavr.control.Either::get);
    }
    public static  <T,R> Vector<R> tailRecEither(T initial, Function<? super T, ? extends Vector<? extends cyclops.control.Either<T, R>>> fn) {
        Vector<cyclops.control.Either<T, R>> next = Vector.of(cyclops.control.Either.left(initial));

        boolean newValue[] = {true};
        for(;;){

            next = next.flatMap(e -> e.visit(s -> {
                        newValue[0]=true;
                        return fn.apply(s); },
                    p -> {
                        newValue[0]=false;
                        return Vector.of(e);
                    }));
            if(!newValue[0])
                break;

        }

        return next.filter(cyclops.control.Either::isRight).map(e->e.orElse(null));
    }

    /**
     * Perform a For Comprehension over a Vector, accepting 3 generating functions.
     * This results in a four level nested internal iteration over the provided Publishers.
     *
     *  <pre>
     * {@code
     *
     *   import static cyclops.Vectors.forEach4;
     *
    forEach4(IntVector.range(1,10).boxed(),
    a-> Vector.iterate(a,i->i+1).limit(10),
    (a,b) -> Vector.<Integer>of(a+b),
    (a,b,c) -> Vector.<Integer>just(a+b+c),
    Tuple::tuple)
     *
     * }
     * </pre>
     *
     * @param value1 top level Vector
     * @param value2 Nested Vector
     * @param value3 Nested Vector
     * @param value4 Nested Vector
     * @param yieldingFunction  Generates a result per combination
     * @return Vector with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, T3, R1, R2, R3, R> Vector<R> forEach4(Vector<? extends T1> value1,
                                                               Function<? super T1, ? extends Vector<R1>> value2,
                                                               BiFunction<? super T1, ? super R1, ? extends Vector<R2>> value3,
                                                               Function3<? super T1, ? super R1, ? super R2, ? extends Vector<R3>> value4,
                                                               Function4<? super T1, ? super R1, ? super R2, ? super R3, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Vector<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Vector<R2> b = value3.apply(in,ina);
                return b.flatMap(inb -> {
                    Vector<R3> c = value4.apply(in,ina,inb);
                    return c.map(in2 -> yieldingFunction.apply(in, ina, inb, in2));
                });

            });

        });

    }

    /**
     * Perform a For Comprehension over a Vector, accepting 3 generating function.
     * This results in a four level nested internal iteration over the provided Publishers.
     * <pre>
     * {@code
     *
     *  import static com.oath.cyclops.reactor.Vectores.forEach4;
     *
     *  forEach4(IntVector.range(1,10).boxed(),
    a-> Vector.iterate(a,i->i+1).limit(10),
    (a,b) -> Vector.<Integer>just(a+b),
    (a,b,c) -> Vector.<Integer>just(a+b+c),
    (a,b,c,d) -> a+b+c+d <100,
    Tuple::tuple);
     *
     * }
     * </pre>
     *
     * @param value1 top level Vector
     * @param value2 Nested Vector
     * @param value3 Nested Vector
     * @param value4 Nested Vector
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return Vector with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, T3, R1, R2, R3, R> Vector<R> forEach4(Vector<? extends T1> value1,
                                                                 Function<? super T1, ? extends Vector<R1>> value2,
                                                                 BiFunction<? super T1, ? super R1, ? extends Vector<R2>> value3,
                                                                 Function3<? super T1, ? super R1, ? super R2, ? extends Vector<R3>> value4,
                                                                 Function4<? super T1, ? super R1, ? super R2, ? super R3, Boolean> filterFunction,
                                                                 Function4<? super T1, ? super R1, ? super R2, ? super R3, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Vector<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Vector<R2> b = value3.apply(in,ina);
                return b.flatMap(inb -> {
                    Vector<R3> c = value4.apply(in,ina,inb);
                    return c.filter(in2->filterFunction.apply(in,ina,inb,in2))
                            .map(in2 -> yieldingFunction.apply(in, ina, inb, in2));
                });

            });

        });
    }

    /**
     * Perform a For Comprehension over a Vector, accepting 2 generating function.
     * This results in a three level nested internal iteration over the provided Publishers.
     *
     * <pre>
     * {@code
     *
     * import static Vectors.forEach3;
     *
     * forEach(IntVector.range(1,10).boxed(),
    a-> Vector.iterate(a,i->i+1).limit(10),
    (a,b) -> Vector.<Integer>of(a+b),
    Tuple::tuple);
     *
     * }
     * </pre>
     *
     *
     * @param value1 top level Vector
     * @param value2 Nested Vector
     * @param value3 Nested Vector
     * @param yieldingFunction Generates a result per combination
     * @return Vector with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, R1, R2, R> Vector<R> forEach3(Vector<? extends T1> value1,
                                                         Function<? super T1, ? extends Vector<R1>> value2,
                                                         BiFunction<? super T1, ? super R1, ? extends Vector<R2>> value3,
                                                         Function3<? super T1, ? super R1, ? super R2, ? extends R> yieldingFunction) {

        return value1.flatMap(in -> {

            Vector<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Vector<R2> b = value3.apply(in,ina);
                return b.map(in2 -> yieldingFunction.apply(in, ina, in2));
            });


        });


    }

    /**
     * Perform a For Comprehension over a Vector, accepting 2 generating function.
     * This results in a three level nested internal iteration over the provided Publishers.
     * <pre>
     * {@code
     *
     * import static Vectors.forEach;
     *
     * forEach(IntVector.range(1,10).boxed(),
    a-> Vector.iterate(a,i->i+1).limit(10),
    (a,b) -> Vector.<Integer>of(a+b),
    (a,b,c) ->a+b+c<10,
    Tuple::tuple)
    .toVectorX();
     * }
     * </pre>
     *
     * @param value1 top level Vector
     * @param value2 Nested publisher
     * @param value3 Nested publisher
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T1, T2, R1, R2, R> Vector<R> forEach3(Vector<? extends T1> value1,
                                                         Function<? super T1, ? extends Vector<R1>> value2,
                                                         BiFunction<? super T1, ? super R1, ? extends Vector<R2>> value3,
                                                         Function3<? super T1, ? super R1, ? super R2, Boolean> filterFunction,
                                                         Function3<? super T1, ? super R1, ? super R2, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Vector<R1> a = value2.apply(in);
            return a.flatMap(ina -> {
                Vector<R2> b = value3.apply(in,ina);
                return b.filter(in2->filterFunction.apply(in,ina,in2))
                        .map(in2 -> yieldingFunction.apply(in, ina, in2));
            });



        });
    }

    /**
     * Perform a For Comprehension over a Vector, accepting an additonal generating function.
     * This results in a two level nested internal iteration over the provided Publishers.
     *
     * <pre>
     * {@code
     *
     *  import static Vectors.forEach2;
     *  forEach(IntVector.range(1, 10).boxed(),
     *          i -> Vector.range(i, 10), Tuple::tuple)
    .forEach(System.out::println);

    //(1, 1)
    (1, 2)
    (1, 3)
    (1, 4)
    ...
     *
     * }</pre>
     *
     * @param value1 top level Vector
     * @param value2 Nested publisher
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T, R1, R> Vector<R> forEach2(Vector<? extends T> value1,
                                                Function<? super T, Vector<R1>> value2,
                                                BiFunction<? super T, ? super R1, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Vector<R1> a = value2.apply(in);
            return a.map(in2 -> yieldingFunction.apply(in,  in2));
        });

    }

    /**
     *
     * <pre>
     * {@code
     *
     *   import static Vectors.forEach2;
     *
     *   forEach(IntVector.range(1, 10).boxed(),
     *           i -> Vector.range(i, 10),
     *           (a,b) -> a>2 && b<10,
     *           Tuple::tuple)
    .forEach(System.out::println);

    //(3, 3)
    (3, 4)
    (3, 5)
    (3, 6)
    (3, 7)
    (3, 8)
    (3, 9)
    ...

     *
     * }</pre>
     *
     *
     * @param value1 top level Vector
     * @param value2 Nested publisher
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return
     */
    public static <T, R1, R> Vector<R> forEach2(Vector<? extends T> value1,
                                                Function<? super T, ? extends Vector<R1>> value2,
                                                BiFunction<? super T, ? super R1, Boolean> filterFunction,
                                                BiFunction<? super T, ? super R1, ? extends R> yieldingFunction) {


        return value1.flatMap(in -> {

            Vector<R1> a = value2.apply(in);
            return a.filter(in2->filterFunction.apply(in,in2))
                    .map(in2 -> yieldingFunction.apply(in,  in2));
        });
    }


}
