package cyclops.collections.vavr;

import java.util.AbstractQueue;
import java.util.Collection;
import java.util.Iterator;
import java.util.Optional;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import java.util.stream.Stream;

import com.oath.cyclops.data.collections.extensions.CollectionX;
import com.oath.cyclops.data.collections.extensions.lazy.immutable.LazyPersistentQueueX;
import com.oath.cyclops.types.Unwrapable;
import com.oath.cyclops.types.foldable.Evaluation;
import com.oath.cyclops.types.persistent.PersistentQueue;
import cyclops.collections.immutable.PersistentQueueX;
import cyclops.collections.immutable.VectorX;
import cyclops.collections.mutable.QueueX;
import cyclops.function.Reducer;
import cyclops.reactive.ReactiveSeq;
import cyclops.data.tuple.Tuple2;



import io.vavr.collection.Queue;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.experimental.Wither;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class VavrQueueX<T> extends AbstractQueue<T> implements PersistentQueue<T>, Unwrapable {
    public static <T> PersistentQueueX<T> queueX(ReactiveSeq<T> stream){
        return fromStream(stream);
    }
    @Override
    public <R> R unwrap() {
        return (R)this.list;
    }

    public static <T> PersistentQueueX<T> copyFromCollection(CollectionX<T> vec) {

        return VavrQueueX.<T>empty()
                .plusAll(vec);

    }
    public static <T> PersistentQueueX<T> from(Queue<T> q) {
        return fromPersistentQueue(new VavrQueueX<>(q), toPersistentQueue());
    }
    /**
     * Create a LazyPersistentQueueX from a Stream
     *
     * @param stream to construct a LazyQueueX from
     * @return LazyPersistentQueueX
     */
    public static <T> LazyPersistentQueueX<T> fromStream(Stream<T> stream) {
        return new LazyPersistentQueueX<T>(null, ReactiveSeq.fromStream(stream),toPersistentQueue(), Evaluation.LAZY);
    }

    /**
     * Create a LazyPersistentQueueX that contains the Integers between start and end
     *
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyPersistentQueueX<Integer> range(int start, int end) {
        return fromStream(ReactiveSeq.range(start, end));
    }

    /**
     * Create a LazyPersistentQueueX that contains the Longs between start and end
     *
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyPersistentQueueX<Long> rangeLong(long start, long end) {
        return fromStream(ReactiveSeq.rangeLong(start, end));
    }

    /**
     * Unfold a function into a ListX
     *
     * <pre>
     * {@code
     *  LazyPersistentQueueX.unfold(1,i->i<=6 ? Optional.of(Tuple.tuple(i,i+1)) : Optional.empty());
     *
     * //(1,2,3,4,5)
     *
     * }</pre>
     *
     * @param seed Initial value
     * @param unfolder Iteratively applied function, terminated by an empty Optional
     * @return ListX generated by unfolder function
     */
    public static <U, T> LazyPersistentQueueX<T> unfold(U seed, Function<? super U, Option<Tuple2<T, U>>> unfolder) {
        return fromStream(ReactiveSeq.unfold(seed, unfolder));
    }

    /**
     * Generate a LazyPersistentQueueX from the provided Supplier up to the provided limit number of times
     *
     * @param limit Max number of elements to generate
     * @param s Supplier to generate ListX elements
     * @return ListX generated from the provided Supplier
     */
    public static <T> LazyPersistentQueueX<T> generate(long limit, Supplier<T> s) {

        return fromStream(ReactiveSeq.generate(s)
                                      .limit(limit));
    }

    /**
     * Create a LazyPersistentQueueX by iterative application of a function to an initial element up to the supplied limit number of times
     *
     * @param limit Max number of elements to generate
     * @param seed Initial element
     * @param f Iteratively applied to each element to generate the next element
     * @return ListX generated by iterative application
     */
    public static <T> LazyPersistentQueueX<T> iterate(long limit, final T seed, final UnaryOperator<T> f) {
        return fromStream(ReactiveSeq.iterate(seed, f)
                                      .limit(limit));
    }

    /**
     * <pre>
     * {@code
     * PersistentQueue<Integer> q = VavrQueueX.<Integer>toPersistentQueue()
                                          .mapReduce(Stream.of(1,2,3,4));
     *
     * }
     * </pre>
     * @return Reducer for PersistentQueue
     */
    public static <T> Reducer<PersistentQueue<T>,T> toPersistentQueue() {
        return Reducer.<PersistentQueue<T>> of(VavrQueueX.emptyPersistentQueue(), (final PersistentQueue<T> a) -> b -> a.plusAll(b), (final T x) -> VavrQueueX.singleton(x));
    }
    public static <T> VavrQueueX<T> emptyPersistentQueue(){
        return new VavrQueueX<>(Queue.empty());

    }
    public static <T> LazyPersistentQueueX<T> empty(){
        return fromPersistentQueue(new VavrQueueX<>(Queue.empty()),toPersistentQueue());

    }
    private static <T> LazyPersistentQueueX<T> fromPersistentQueue(PersistentQueue<T> ts, Reducer<PersistentQueue<T>,T> pQueueReducer) {
        return new LazyPersistentQueueX<T>(ts,null,pQueueReducer, Evaluation.LAZY);
    }
    public static <T> LazyPersistentQueueX<T> singleton(T t){
        return  fromPersistentQueue(new VavrQueueX<>(Queue.of(t)),toPersistentQueue());
    }
    public static <T> LazyPersistentQueueX<T> of(T... t){
       return  fromPersistentQueue(new VavrQueueX<>(Queue.of(t)),toPersistentQueue());
    }
    public static <T> LazyPersistentQueueX<T> ofAll(T... t){
        return  fromPersistentQueue(new VavrQueueX<>(Queue.of(t)),toPersistentQueue());
    }
    public static <T> LazyPersistentQueueX<T> PersistentQueue(Queue<T> q) {
        return fromPersistentQueue(new VavrQueueX<>(q), toPersistentQueue());
    }
    @SafeVarargs
    public static <T> LazyPersistentQueueX<T> PersistentQueue(T... elements){
        return fromPersistentQueue(of(elements),toPersistentQueue());
    }
    @Wither
    private final Queue<T> list;

    @Override
    public PersistentQueue<T> plus(T e) {
        return withList(list.prepend(e));
    }

    @Override
    public PersistentQueue<T> plusAll(Collection<? extends T> l) {
        return withList(list.prependAll(l));
    }



    @Override
    public PersistentQueue<T> minus(Object e) {
        return withList(list.remove((T)e));
    }

    @Override
    public PersistentQueue<T> minusAll(Collection<?> l) {
        return withList(list.removeAll((Collection)l));
    }



    @Override
    public int size() {
        return list.size();
    }

    @Override
    public T peek() {
       return list.peek();
    }

    @Override
    public org.pcollections.PersistentQueue<T> minus() {
        return withList(list.drop(1));
    }

    @Override
    public boolean offer(T o) {
        throw new UnsupportedOperationException();
    }

    @Override
    public T poll() {
        return list.get();
    }

    @Override
    public Iterator<T> iterator() {
        return list.iterator();
    }




}
