package cyclops.collections.vavr;


import com.oath.cyclops.data.collections.extensions.CollectionX;
import com.oath.cyclops.data.collections.extensions.lazy.immutable.LazyPersistentSortedSetX;
import com.oath.cyclops.types.Unwrapable;
import com.oath.cyclops.types.foldable.Evaluation;
import cyclops.collections.immutable.OrderedSetX;
import cyclops.function.Reducer;
import cyclops.reactive.ReactiveSeq;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.experimental.Wither;
import cyclops.data.tuple.Tuple2;
import org.pcollections.PersistentSortedSet;
import io.vavr.collection.BitSet;

import java.util.*;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import java.util.stream.Stream;

/*
 * BitSet is experimental / not ready for prime time
 */
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class VavrBitSetX extends AbstractSet<Integer>implements PersistentSortedSet<Integer>, Unwrapable {

    public static OrderedSetX<Integer> bitSetX(ReactiveSeq<Integer> stream){
        return fromStream(stream);
    }

    @Override
    public <R> R unwrap() {
        return (R)set;
    }

    /**
     * Create a LazyPersistentSortedSetX from a Stream
     *
     * @param stream to construct a LazyQueueX from
     * @return LazyPersistentSortedSetX
     */
    public static <T extends Comparable<? super T>> LazyPersistentSortedSetX<Integer> fromStream(Stream<Integer> stream) {
        Reducer<PersistentSortedSet<Integer>> reducer = VavrBitSetX.toPersistentSortedSet();
        return new LazyPersistentSortedSetX( null, ReactiveSeq.<Integer>fromStream(stream),
                                  reducer, Evaluation.LAZY
                                   );
    }

    /**
     * Create a LazyPersistentSortedSetX that contains the Integers between start and end
     *
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range SetX
     */
    public static LazyPersistentSortedSetX<Integer> range(int start, int end) {
        return fromStream(ReactiveSeq.range(start, end));
    }



    /**
     * Unfold a function into a SetX
     *
     * <pre>
     * {@code
     *  LazyPersistentSortedSetX.unfold(1,i->i<=6 ? Optional.of(Tuple.tuple(i,i+1)) : Optional.empty());
     *
     * //(1,2,3,4,5)
     *
     * }</pre>
     *
     * @param seed Initial value
     * @param unfolder Iteratively applied function, terminated by an empty Optional
     * @return SetX generated by unfolder function
     */
    public static  LazyPersistentSortedSetX<Integer> unfold(Integer seed, Function<? super Integer, Optional<Tuple2<Integer, Integer>>> unfolder) {
        return fromStream(ReactiveSeq.unfold(seed, unfolder));
    }

    /**
     * Generate a LazyPersistentSortedSetX from the provided Supplier up to the provided limit number of times
     *
     * @param limit Max number of elements to generate
     * @param s Supplier to generate SetX elements
     * @return SetX generated from the provided Supplier
     */
    public static <T extends Comparable<? super T>> LazyPersistentSortedSetX generate(long limit, Supplier s) {

        return fromStream(ReactiveSeq.generate(s)
                                     .limit(limit));
    }

    /**
     * Create a LazyPersistentSortedSetX by iterative application of a function to an initial element up to the supplied limit number of times
     *
     * @param limit Max number of elements to generate
     * @param seed Initial element
     * @param f Iteratively applied to each element to generate the next element
     * @return SetX generated by iterative application
     */
    public static <T extends Comparable<? super T>> LazyPersistentSortedSetX iterate(long limit, final T seed, final UnaryOperator f) {
        return fromStream(ReactiveSeq.iterate(seed, f)
                                     .limit(limit));
    }

    /**
     * <pre>
     * {@code
     * PersistentSortedSet<Integer> q = JSPersistentSortedSet.<Integer>toPersistentSortedSet()
                                     .mapReduce(Stream.of(1,2,3,4));
     *
     * }
     * </pre>
     * @return Reducer for PersistentSortedSet
     */
    public static  Reducer<PersistentSortedSet<Integer>> toPersistentSortedSet() {
        return Reducer.<PersistentSortedSet<Integer>> of(VavrBitSetX.emptyPersistentSortedSet(),
                                                 (final PersistentSortedSet<Integer> a) -> b -> a.plusAll(b),
                                      (final Integer x) -> VavrBitSetX.singleton(x));
    }



    public static VavrBitSetX fromSet(BitSet set) {
        return new VavrBitSetX(
                                 set);
    }


    public static VavrBitSetX emptyPersistentSortedSet() {
        return new VavrBitSetX(BitSet.empty());
    }


    public static LazyPersistentSortedSetX<Integer> empty() {


        return fromPersistentSortedSet(new VavrBitSetX(BitSet.empty()),
                                                toPersistentSortedSet());
    }

    public static  LazyPersistentSortedSetX<Integer> singleton(Integer t) {
        return of(t);
    }

    public static  LazyPersistentSortedSetX<Integer> of(Integer... t) {


       BitSet vec = BitSet.of(t);
       return fromPersistentSortedSet(new VavrBitSetX(
                                                       vec),
                                     toPersistentSortedSet());
   }



    private static <T> LazyPersistentSortedSetX<T> fromPersistentSortedSet(PersistentSortedSet<T> ordered, Reducer<PersistentSortedSet<T>> reducer) {
        return  new LazyPersistentSortedSetX<T>(ordered,null,reducer, Evaluation.LAZY);
    }
    public static  LazyPersistentSortedSetX<Integer> PersistentSortedSet(BitSet q) {
        return fromPersistentSortedSet(new VavrBitSetX(
                                                         q),
                                      toPersistentSortedSet());
    }

    @SafeVarargs
    public static  LazyPersistentSortedSetX<Integer> PersistentSortedSet(Integer... elements) {
        return fromPersistentSortedSet(of(elements), toPersistentSortedSet());
    }

    @Wither
    private final BitSet set;

    @Override
    public VavrBitSetX plus(Integer e) {

        return withSet(set.add((int)e));
    }

    @Override
    public VavrBitSetX plusAll(Collection<? extends Integer> l) {


        BitSet vec = set.addAll(l);


        return withSet(vec);

    }






    @Override
    public PersistentSortedSet<Integer> minus(Object e) {
        if(e instanceof Integer){
            Integer i =(Integer)e;
            return withSet((BitSet)set.remove((int)i));
        }
        else
            return this;

    }

    @Override
    public PersistentSortedSet<Integer> minusAll(Collection<?> s) {

        return withSet((BitSet)set.removeAll(s));
    }




    @Override
    public int size() {
        return set.size();
    }

    @Override
    public io.vavr.collection.Iterator<Integer> iterator() {
        return set.iterator();
    }

    @Override
    public Integer get(int index) {
        return (Integer) set.toVector().apply(index);
    }

    @Override
    public int indexOf(Object o) {
        return set.toVector().indexOf(o);
    }





    public static OrderedSetX<Integer> copyFromCollection(CollectionX<Integer> vec) {
        OrderedSetX<Integer> res = VavrBitSetX.empty()
                .plusAll(vec);
        return res;
    }

}
