package cyclops.collections.vavr;

import java.util.AbstractList;
import java.util.Collection;
import java.util.Optional;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import java.util.stream.Stream;

import com.oath.cyclops.data.collections.extensions.CollectionX;
import com.oath.cyclops.data.collections.extensions.lazy.immutable.LazyLinkedListX;
import com.oath.cyclops.data.collections.extensions.lazy.immutable.LazyPersistentListX;
import com.oath.cyclops.types.Unwrapable;
import com.oath.cyclops.types.foldable.Evaluation;
import cyclops.collections.immutable.VectorX;
import cyclops.function.Reducer;
import cyclops.reactive.ReactiveSeq;
import io.vavr.collection.List;
import cyclops.data.tuple.Tuple2;
import org.pcollections.PersistentList;


import io.vavr.collection.Vector;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.experimental.Wither;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class VavrVectorX<T> extends AbstractList<T> implements PersistentList<T>, Unwrapable {

    public static <T> VectorX<T> vectorX(ReactiveSeq<T> stream){
        return fromStream(stream);
    }
    @Override
    public <R> R unwrap() {
        return (R)vector;
    }

    public static <T> VectorX<T> copyFromCollection(CollectionX<T> vec) {

        return VavrVectorX.<T>empty()
                .plusAll(vec);

    }
    /**
     * Create a LazyPersistentListX from a Stream
     *
     * @param stream to construct a LazyQueueX from
     * @return LazyPersistentListX
     */
    public static <T> LazyPersistentListX<T> fromStream(Stream<T> stream) {
        return new LazyPersistentListX<T>(null, ReactiveSeq.fromStream(stream),toPersistentList(), Evaluation.LAZY);
    }

    /**
     * Create a LazyPersistentListX that contains the Integers between start and end
     *
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyPersistentListX<Integer> range(int start, int end) {
        return fromStream(ReactiveSeq.range(start, end));
    }

    /**
     * Create a LazyPersistentListX that contains the Longs between start and end
     *
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyPersistentListX<Long> rangeLong(long start, long end) {
        return fromStream(ReactiveSeq.rangeLong(start, end));
    }

    /**
     * Unfold a function into a ListX
     *
     * <pre>
     * {@code
     *  LazyPersistentListX.unfold(1,i->i<=6 ? Optional.of(Tuple.tuple(i,i+1)) : Optional.empty());
     *
     * //(1,2,3,4,5)
     *
     * }</pre>
     *
     * @param seed Initial value
     * @param unfolder Iteratively applied function, terminated by an empty Optional
     * @return ListX generated by unfolder function
     */
    public static <U, T> LazyPersistentListX<T> unfold(U seed, Function<? super U, Option<Tuple2<T, U>>> unfolder) {
        return fromStream(ReactiveSeq.unfold(seed, unfolder));
    }

    /**
     * Generate a LazyPersistentListX from the provided Supplier up to the provided limit number of times
     *
     * @param limit Max number of elements to generate
     * @param s Supplier to generate ListX elements
     * @return ListX generated from the provided Supplier
     */
    public static <T> LazyPersistentListX<T> generate(long limit, Supplier<T> s) {

        return fromStream(ReactiveSeq.generate(s)
                                      .limit(limit));
    }

    /**
     * Create a LazyPersistentListX by iterative application of a function to an initial element up to the supplied limit number of times
     *
     * @param limit Max number of elements to generate
     * @param seed Initial element
     * @param f Iteratively applied to each element to generate the next element
     * @return ListX generated by iterative application
     */
    public static <T> LazyPersistentListX<T> iterate(long limit, final T seed, final UnaryOperator<T> f) {
        return fromStream(ReactiveSeq.iterate(seed, f)
                                      .limit(limit));
    }

    /**
     * <pre>
     * {@code
     * PersistentList<Integer> q = JSPersistentList.<Integer>toPersistentList()
                                     .mapReduce(Stream.of(1,2,3,4));
     *
     * }
     * </pre>
     * @return Reducer for PersistentList
     */
    public static <T> Reducer<PersistentList<T>,T> toPersistentList() {
        return Reducer.<PersistentList<T>> of(VavrVectorX.emptyPersistentList(), (final PersistentList<T> a) -> b -> a.plusAll(b), (final T x) -> VavrVectorX.singleton(x));
    }
    public static <T> VavrVectorX<T> emptyPersistentList(){
        return new VavrVectorX<>(Vector.empty());
    }
    public static <T> LazyPersistentListX<T> empty(){
        return fromPersistentList(new VavrVectorX<>(Vector.empty()), toPersistentList());
    }
    private static <T> LazyPersistentListX<T> fromPersistentList(PersistentList<T> vec, Reducer<PersistentList<T>,T> pVectorReducer) {
        return new LazyPersistentListX<T>(vec,null, pVectorReducer,Evaluation.LAZY);
    }
    public static <T> LazyPersistentListX<T> singleton(T t){
        return fromPersistentList(new VavrVectorX<>(Vector.of(t)), toPersistentList());
    }
    public static <T> LazyPersistentListX<T> of(T... t){
        return fromPersistentList(new VavrVectorX<>(Vector.of(t)), toPersistentList());
    }
    public static <T> LazyPersistentListX<T> ofAll(Vector<T> t){
        return fromPersistentList(new VavrVectorX<>(t), toPersistentList());
    }
    public static <T> LazyPersistentListX<T> PersistentList(Vector<T> q) {
        return fromPersistentList(new VavrVectorX<T>(q), toPersistentList());
    }
    public static <T> LazyPersistentListX<T> from(Vector<T> q) {
        return PersistentList(q);
    }
    @SafeVarargs
    public static <T> LazyPersistentListX<T> PersistentList(T... elements){
        return fromPersistentList(of(elements),toPersistentList());
    }
    @Wither
    private final Vector<T> vector;

    @Override
    public PersistentList<T> plus(T e) {
        return withVector(vector.append(e));
    }

    @Override
    public PersistentList<T> plusAll(Collection<? extends T> list) {
        return withVector(vector.appendAll(list));
    }

    @Override
    public PersistentList<T> with(int i, T e) {
        return withVector(vector.insert(i,e));
    }

    @Override
    public PersistentList<T> plus(int i, T e) {
        return withVector(vector.insert(i,e));
    }

    @Override
    public PersistentList<T> plusAll(int i, Collection<? extends T> list) {
        return withVector(vector.insertAll(i,list));
    }

    @Override
    public PersistentList<T> minus(Object e) {
        return withVector(vector.remove((T)e));
    }

    @Override
    public PersistentList<T> minusAll(Collection<?> list) {
        return withVector(vector.removeAll((Collection)list));
    }

    @Override
    public PersistentList<T> minus(int i) {
        return withVector(vector.removeAt(i));
    }

    @Override
    public PersistentList<T> subList(int start, int end) {
        return withVector(vector.subSequence(start, end));
    }

    @Override
    public T get(int index) {
        return vector.get(index);
    }

    @Override
    public int size() {
        return vector.size();
    }


}
