package com.aol.cyclops.rx;

import java.util.function.BiFunction;
import java.util.function.Function;

import org.reactivestreams.Publisher;

import com.aol.cyclops.control.AnyM;
import com.aol.cyclops.control.For;
import com.aol.cyclops.rx.transformer.ObservableT;
import com.aol.cyclops.rx.transformer.ObservableTSeq;
import com.aol.cyclops.types.anyM.AnyMSeq;
import com.aol.cyclops.util.function.QuadFunction;
import com.aol.cyclops.util.function.TriFunction;

import lombok.experimental.UtilityClass;
import rx.Observable;

/**
 * Companion class for working with RxJava Observable Transformers
 * Observable Transformers allow direct manipulation of nested Observables
 * 
 * @author johnmcclean
 *
 */
@UtilityClass
public class ObservableTs {
    
    /**
     * Construct an AnyM type from an Observable Transformer. This allows the Observable Transformer to be manipulated according to a standard interface
     * along with a vast array of other Java Monad implementations
     * 
     * <pre>
     * {@code 
     *    
     *    AnyMSeq<Integer> obsT =ObservableT.fromIterable(ListX.of(Observable.just(1,2,3)));
     *    AnyMSeq<Integer> transformedObsT = myGenericOperation(obsT);
     *    
     *    public AnyMSeq<Integer> myGenericOperation(AnyMSeq<Integer> monad);
     * }
     * </pre>
     * 
     * @param obs ObservableT to wrap inside an AnyM
     * @return AnyMSeq wrapping an ObservableT
     */
    public static <T> AnyMSeq<T> anyM(ObservableT<T> obs) {
        return AnyM.ofSeq(obs);
    }
    /**
     * Construct an ObservableT from a Publisher containing nested Observables
     * 
     * @param nested Publisher containing nested Observables
     * @return Observable Transformer for manipulating nested Observables
     */
    public static <T> ObservableTSeq<T> observableT(Publisher<Observable<T>> nested) {
        return ObservableT.fromPublisher(nested);
    }
    /**
     * Construct an ObservableT from an Observable containing nested Observables
     * 
     * @param nested Observable containing nested Obsvervables
     * @return Observable Transformer for manipulating nested Observables
     */
    public static <T> ObservableTSeq<T> observableT(Observable<Observable<T>> nested) {
        return ObservableT.fromObservable(nested);
    }

    /**
     * Perform a For Comprehension over a  ObservableT, accepting 3 generating functions. 
     * This results in a four level nested internal iteration over the provided Publishers.
     * 
     *  <pre>
     * {@code
     *    
     *   import static com.aol.cyclops.rx.ObservableTs.forEach;
     *   
     *    ObservableT<Integer> obsT = ObservableT.fromIterable(Arrays.asList(Observable.range(10,2),Observable.range(100,2)));
     *    
         forEach(obsT, 
                  a-> ReactiveSeq.iterate(a,i->i+1).limit(2),
                  (a,b)-> ReactiveSeq.iterate(a,i->i+1).limit(2),
                  (a,b,c)-> ReactiveSeq.iterate(a,i->i+1).limit(2),
               Tuple::tuple)
               .forEach(System.out::println);
               
     //(10, 10, 10, 10)
       (11, 11, 11, 11)
       (100, 100, 100, 100)
       (101, 101, 101, 101)        
    * 
    * }
    * </pre>
    * 
    * @param value1 top level ObservableT
    * @param value2 Nested publisher
    * @param value3 Nested publisher
    * @param value4 Nested publisher
    * @param yieldingFunction  Generates a result per combination
    * @return ObservableT with an element per combination of nested publishers generated by the yielding function
    */
    public static <T1, T2, T3, R1, R2, R3, R> ObservableT<R> forEach(ObservableT<? extends T1> value1,
            Function<? super T1, ? extends Publisher<R1>> value2,
            BiFunction<? super T1, ? super R1, ? extends Publisher<R2>> value3,
            TriFunction<? super T1, ? super R1, ? super R2, ? extends Publisher<R3>> value4,
            QuadFunction<? super T1, ? super R1, ? super R2, ? super R3, ? extends R> yieldingFunction) {

        return AnyM.ofSeq(For.anyM(anyM(value1))
                             .anyM(a -> AnyM.fromPublisher(value2.apply(a)))
                             .anyM(a -> b ->  AnyM.fromPublisher(value3.apply(a, b)))
                             .anyM(a -> b -> c ->  AnyM.fromPublisher(value4.apply(a, b, c)))
                             .yield4(yieldingFunction)
                             .unwrap())
                   .unwrap();

    }
    /**
     * Perform a For Comprehension over an ObservableT, accepting 3 generating functions. 
     * This results in a four level nested internal iteration over the provided Publishers.
     * 
     *  <pre>
     * {@code
     *    
     *   import static com.aol.cyclops.rx.ObservableTs.forEach;
     *   
     *    ObservableT<Integer> obsT = ObservableT.fromIterable(Arrays.asList(Observable.range(10,2),Observable.range(100,2)));
     *    
         forEach(obs, 
                  a-> ReactiveSeq.iterate(a,i->i+1).limit(2),
                  (a,b)-> ReactiveSeq.iterate(a,i->i+1).limit(2),
                  (a,b,c)-> ReactiveSeq.iterate(a,i->i+1).limit(2),
                  (a,b,c,d)->a+b+c+d<102,
               Tuple::tuple)
               .forEach(System.out::println);
               
     //(10, 10, 10, 10)
       (11, 11, 11, 11)       
    * 
    * }
    * </pre>
     * @param value1 top level ObservableT
     * @param value2 Nested publisher
     * @param value3 Nested publisher
     * @param value4 Nested publisher
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return ObservableT with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, T3, R1, R2, R3, R> ObservableT<R> forEach(ObservableT<? extends T1> value1,
            Function<? super T1, ? extends Publisher<R1>> value2,
            BiFunction<? super T1, ? super R1, ? extends Publisher<R2>> value3,
            TriFunction<? super T1, ? super R1, ? super R2, ? extends Publisher<R3>> value4,
            QuadFunction<? super T1, ? super R1, ? super R2, ? super R3, Boolean> filterFunction,
            QuadFunction<? super T1, ? super R1, ? super R2, ? super R3, ? extends R> yieldingFunction) {

        return AnyM.ofSeq(For.anyM(anyM(value1))
                             .anyM(a ->  AnyM.fromPublisher(value2.apply(a)))
                             .anyM(a -> b ->  AnyM.fromPublisher(value3.apply(a, b)))
                             .anyM(a -> b -> c ->  AnyM.fromPublisher(value4.apply(a, b, c)))
                             .filter(a -> b -> c -> d -> filterFunction.apply(a, b, c, d))
                             .yield4(yieldingFunction)
                             .unwrap())
                   .unwrap();

    }
    /**
     * Perform a For Comprehension over a  ObservableT, accepting 2 generating functions. 
     * This results in a three level nested internal iteration over the provided Publishers.
     * 
     *  <pre>
     * {@code
     *    
     *   import static com.aol.cyclops.rx.ObservableTs.forEach;
     *   
     *    ObservableT<Integer> obsT = ObservableT.fromIterable(Arrays.asList(Observable.range(10,2),Observable.range(100,2)));
     *    
         forEach(obsT, 
                  a-> ReactiveSeq.iterate(a,i->i+1).limit(2),
                  (a,b)-> ReactiveSeq.iterate(a,i->i+1).limit(2),
               Tuple::tuple)
               .forEach(System.out::println);
               
      
    * 
    * }
    * </pre>
    * 
    * @param value1 top level ObservableT
    * @param value2 Nested publisher
    * @param value3 Nested publisher
    * @param yieldingFunction  Generates a result per combination
    * @return ObservableT with an element per combination of nested publishers generated by the yielding function
    */
    public static <T1, T2, R1, R2, R> ObservableT<R> forEach(ObservableT<? extends T1> value1,
            Function<? super T1, ? extends Publisher<R1>> value2,
            BiFunction<? super T1, ? super R1, ? extends Publisher<R2>> value3,
            TriFunction<? super T1, ? super R1, ? super R2, ? extends R> yieldingFunction) {

        return AnyM.ofSeq(For.anyM(anyM(value1))
                             .anyM(a ->  AnyM.fromPublisher(value2.apply(a)))
                             .anyM(a -> b ->  AnyM.fromPublisher(value3.apply(a, b)))
                             .yield3(yieldingFunction)
                             .unwrap())
                   .unwrap();

    }

    /**
     * Perform a For Comprehension over an ObservableT, accepting 2 generating functions. 
     * This results in a three level nested internal iteration over the provided Publishers.
     * 
     *  <pre>
     * {@code
     *    
     *   import static com.aol.cyclops.rx.ObservableTs.forEach;
     *   
     *    ObservableT<Integer> obsT = ObservableT.fromIterable(Arrays.asList(Observable.range(10,2),Observable.range(100,2)));
     *    
         forEach(obs, 
                  a-> ReactiveSeq.iterate(a,i->i+1).limit(2),
                  (a,b)-> ReactiveSeq.iterate(a,i->i+1).limit(2),
                  (a,b,c)->a+b+c<102,
               Tuple::tuple)
               .forEach(System.out::println);
    
    * 
    * }
    * </pre>
     * @param value1 top level ObservableT
     * @param value2 Nested publisher
     * @param value3 Nested publisher
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return ObservableT with an element per combination of nested publishers generated by the yielding function
     */
    public static <T1, T2, R1, R2, R> ObservableT<R> forEach(ObservableT<? extends T1> value1,
            Function<? super T1, ? extends Publisher<R1>> value2,
            BiFunction<? super T1, ? super R1, ? extends Publisher<R2>> value3,
            TriFunction<? super T1, ? super R1, ? super R2, Boolean> filterFunction,
            TriFunction<? super T1, ? super R1, ? super R2, ? extends R> yieldingFunction) {

        return AnyM.ofSeq(For.anyM(anyM(value1))
                             .anyM(a ->  AnyM.fromPublisher(value2.apply(a)))
                             .anyM(a -> b ->  AnyM.fromPublisher(value3.apply(a, b)))
                             .filter(a -> b -> c -> filterFunction.apply(a, b, c))
                             .yield3(yieldingFunction)
                             .unwrap())
                   .unwrap();

    }
    /**
     * Perform a For Comprehension over a  ObservableT, accepting a generating function. 
     * This results in a two level nested internal iteration over the provided Publishers.
     * 
     *  <pre>
     * {@code
     *    
     *   import static com.aol.cyclops.rx.ObservableTs.forEach;
     *   
     *    ObservableT<Integer> obsT = ObservableT.fromIterable(Arrays.asList(Observable.range(10,2),Observable.range(100,2)));
     *    
         forEach(obsT, 
                  a-> ReactiveSeq.iterate(a,i->i+1).limit(2),
               Tuple::tuple)
               .forEach(System.out::println);
               
      
    * 
    * }
    * </pre>
    * 
    * @param value1 top level ObservableT
    * @param value2 Nested publisher
    * @param yieldingFunction  Generates a result per combination
    * @return ObservableT with an element per combination of nested publishers generated by the yielding function
    */
    public static <T, R1, R> ObservableT<R> forEach(ObservableT<? extends T> value1,
            Function<? super T, Publisher<R1>> value2,
            BiFunction<? super T, ? super R1, ? extends R> yieldingFunction) {

        return AnyM.ofSeq(For.anyM(anyM(value1))
                             .anyM(a ->  AnyM.fromPublisher(value2.apply(a)))
                             .yield2(yieldingFunction)
                             .unwrap())
                   .unwrap();

    }
    /**
     * Perform a For Comprehension over an ObservableT, accepting a generating function. 
     * This results in a two level nested internal iteration over the provided Publishers.
     * 
     *  <pre>
     * {@code
     *    
     *   import static com.aol.cyclops.rx.ObservableTs.forEach;
     *   
     *    ObservableT<Integer> obsT = ObservableT.fromIterable(Arrays.asList(Observable.range(10,2),Observable.range(100,2)));
     *    
         forEach(obs, 
                  a-> ReactiveSeq.iterate(a,i->i+1).limit(2),
                  (a,b)->a+b<102,
               Tuple::tuple)
               .forEach(System.out::println);
               
      
    * 
    * }
    * </pre>
     * @param value1 top level ObservableT
     * @param value2 Nested publisher
     * @param filterFunction A filtering function, keeps values where the predicate holds
     * @param yieldingFunction Generates a result per combination
     * @return ObservableT with an element per combination of nested publishers generated by the yielding function
     */
    public static <T, R1, R> ObservableT<R> forEach(ObservableT<? extends T> value1,
            Function<? super T, ? extends Publisher<R1>> value2,
            BiFunction<? super T, ? super R1, Boolean> filterFunction,
            BiFunction<? super T, ? super R1, ? extends R> yieldingFunction) {

        return AnyM.ofSeq(For.anyM(anyM(value1))
                             .anyM(a ->  AnyM.fromPublisher(value2.apply(a)))
                             .filter(a -> b -> filterFunction.apply(a, b))
                             .yield2(yieldingFunction)
                             .unwrap())
                   .unwrap();

    }

}
