package com.aol.cyclops.reactor.collections.extensions.standard;

import java.util.Collection;
import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.Optional;
import java.util.Random;
import java.util.Spliterator;
import java.util.function.BiFunction;
import java.util.function.BiPredicate;
import java.util.function.BinaryOperator;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import java.util.stream.Collector;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.jooq.lambda.Seq;
import org.jooq.lambda.tuple.Tuple2;
import org.jooq.lambda.tuple.Tuple3;
import org.jooq.lambda.tuple.Tuple4;
import org.reactivestreams.Publisher;

import com.aol.cyclops.Monoid;
import com.aol.cyclops.control.Matchable.CheckValue1;
import com.aol.cyclops.control.ReactiveSeq;
import com.aol.cyclops.control.Trampoline;
import com.aol.cyclops.control.monads.transformers.seq.ListTSeq;
import com.aol.cyclops.data.async.QueueFactory;
import com.aol.cyclops.data.collections.extensions.standard.ListX;
import com.aol.cyclops.data.collections.extensions.standard.ListXImpl;
import com.aol.cyclops.reactor.Fluxes;
import com.aol.cyclops.reactor.collections.extensions.base.AbstractFluentCollectionX;
import com.aol.cyclops.reactor.collections.extensions.base.LazyFluentCollection;

import lombok.Getter;
import reactor.core.publisher.Flux;

/**
 * An extended List type {@see java.util.List}
 * Extended List operations execute lazily e.g.
 * <pre>
 * {@code 
 *    LazyListX<Integer> q = LazyListX.of(1,2,3)
 *                                      .map(i->i*2);
 * }
 * </pre>
 * The map operation above is not executed immediately. It will only be executed when (if) the data inside the
 * queue is accessed. This allows lazy operations to be chained and executed more efficiently e.g.
 * 
 * <pre>
 * {@code 
 *    LazyListX<Integer> q = LazyListX.of(1,2,3)
 *                                      .map(i->i*2);
 *                                      .filter(i->i<5);
 * }
 * </pre>
 * 
 * The operation above is more efficient than the equivalent operation with a ListX.
 * 
 * @author johnmcclean
 *
 * @param <T> the type of elements held in this collection
 */
public class LazyListX<T> extends AbstractFluentCollectionX<T>implements ListX<T> {
    private final LazyFluentCollection<T, List<T>> lazy;
    @Getter
    private final Collector<T, ?, List<T>> collector;

    /**
     * Create a LazyListX from a Stream
     * 
     * @param stream to construct a LazyQueueX from
     * @return LazyListX
     */
    public static <T> LazyListX<T> fromStreamS(Stream<T> stream) {
        return new LazyListX<T>(
                                Flux.from(ReactiveSeq.fromStream(stream)));
    }

    /**
     * Create a LazyListX that contains the Integers between start and end
     * 
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyListX<Integer> range(int start, int end) {
        return fromStreamS(ReactiveSeq.range(start, end));
    }

    /**
     * Create a LazyListX that contains the Longs between start and end
     * 
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range ListX
     */
    public static LazyListX<Long> rangeLong(long start, long end) {
        return fromStreamS(ReactiveSeq.rangeLong(start, end));
    }

    /**
     * Unfold a function into a ListX
     * 
     * <pre>
     * {@code 
     *  LazyListX.unfold(1,i->i<=6 ? Optional.of(Tuple.tuple(i,i+1)) : Optional.empty());
     * 
     * //(1,2,3,4,5)
     * 
     * }</pre>
     * 
     * @param seed Initial value 
     * @param unfolder Iteratively applied function, terminated by an empty Optional
     * @return ListX generated by unfolder function
     */
    public static <U, T> LazyListX<T> unfold(U seed, Function<? super U, Optional<Tuple2<T, U>>> unfolder) {
        return fromStreamS(ReactiveSeq.unfold(seed, unfolder));
    }

    /**
     * Generate a LazyListX from the provided Supplier up to the provided limit number of times
     * 
     * @param limit Max number of elements to generate
     * @param s Supplier to generate ListX elements
     * @return ListX generated from the provided Supplier
     */
    public static <T> LazyListX<T> generate(long limit, Supplier<T> s) {

        return fromStreamS(ReactiveSeq.generate(s)
                                      .limit(limit));
    }

    /**
     * Create a LazyListX by iterative application of a function to an initial element up to the supplied limit number of times
     * 
     * @param limit Max number of elements to generate
     * @param seed Initial element
     * @param f Iteratively applied to each element to generate the next element
     * @return ListX generated by iterative application
     */
    public static <T> LazyListX<T> iterate(long limit, final T seed, final UnaryOperator<T> f) {
        return fromStreamS(ReactiveSeq.iterate(seed, f)
                                      .limit(limit));
    }

    /**
     * @return A collector that generates a LazyListX
     */
    public static <T> Collector<T, ?, LazyListX<T>> lazyListXCollector() {
        return Collectors.toCollection(() -> LazyListX.of());
    }

    /**
     * @return An empty LazyListX
     */
    public static <T> LazyListX<T> empty() {
        return fromIterable((List<T>) ListX.<T> defaultCollector()
                                           .supplier()
                                           .get());
    }

    /**
     * Create a LazyListX from the specified values
     * <pre>
     * {@code 
     *     ListX<Integer> lazy = LazyListX.of(1,2,3,4,5);
     *     
     *     //lazily map List
     *     ListX<String> mapped = lazy.map(i->"mapped " +i); 
     *     
     *     String value = mapped.get(0); //transformation triggered now
     * }
     * </pre>
     * 
     * @param values To populate LazyListX with
     * @return LazyListX
     */
    @SafeVarargs
    public static <T> LazyListX<T> of(T... values) {
        List<T> res = (List<T>) ListX.<T> defaultCollector()
                                     .supplier()
                                     .get();
        for (T v : values)
            res.add(v);
        return fromIterable(res);
    }

    /**
     * Construct a LazyListX with a single value
     * <pre>
     * {@code 
     *    ListX<Integer> lazy = LazyListX.singleton(5);
     *    
     * }
     * </pre>
     * 
     * 
     * @param value To populate LazyListX with
     * @return LazyListX with a single value
     */
    public static <T> LazyListX<T> singleton(T value) {
        return LazyListX.<T> of(value);
    }

    /**
     * Construct a LazyListX from an Publisher
     * 
     * @param publisher
     *            to construct LazyListX from
     * @return ListX
     */
    public static <T> LazyListX<T> fromPublisher(Publisher<? extends T> publisher) {
        return fromStreamS(ReactiveSeq.fromPublisher((Publisher<T>) publisher));
    }

    /**
     * Construct LazyListX from an Iterable
     * 
     * @param it to construct LazyListX from
     * @return LazyListX from Iterable
     */
    public static <T> LazyListX<T> fromIterable(Iterable<T> it) {
        return fromIterable(ListX.<T> defaultCollector(), it);
    }

    /**
     * Construct a LazyListX from an Iterable, using the specified Collector.
     * 
     * @param collector To generate Lists from, this can be used to create mutable vs immutable Lists (for example), or control List type (ArrayList, LinkedList)
     * @param it Iterable to construct LazyListX from
     * @return Newly constructed LazyListX
     */
    public static <T> LazyListX<T> fromIterable(Collector<T, ?, List<T>> collector, Iterable<T> it) {
        if (it instanceof LazyListX)
            return (LazyListX<T>) it;

        if (it instanceof List)
            return new LazyListX<T>(
                                    (List<T>) it, collector);
        return new LazyListX<T>(
                                Flux.fromIterable(it), collector);
    }

    private LazyListX(List<T> list, Collector<T, ?, List<T>> collector) {
        this.lazy = new LazyCollection<>(
                                         list, null, collector);
        this.collector = collector;
    }

    private LazyListX(List<T> list) {

        this.collector = ListX.defaultCollector();
        this.lazy = new LazyCollection<T, List<T>>(
                                                   list, null, collector);
    }

    private LazyListX(Flux<T> stream, Collector<T, ?, List<T>> collector) {

        this.collector = collector;
        this.lazy = new LazyCollection<>(
                                         null, stream, collector);
    }

    private LazyListX(Flux<T> stream) {

        this.collector = ListX.defaultCollector();
        this.lazy = new LazyCollection<>(
                                         null, stream, collector);
    }

    private LazyListX() {
        this.collector = ListX.defaultCollector();
        this.lazy = new LazyCollection<>(
                                         (List) this.collector.supplier()
                                                              .get(),
                                         null, collector);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Iterable#forEach(java.util.function.Consumer)
     */
    @Override
    public void forEach(Consumer<? super T> action) {
        getList().forEach(action);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Iterable#iterator()
     */
    @Override
    public Iterator<T> iterator() {
        return getList().iterator();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#size()
     */
    @Override
    public int size() {
        return getList().size();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#contains(java.lang.Object)
     */
    @Override
    public boolean contains(Object e) {
        return getList().contains(e);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object o) {
        return getList().equals(o);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#isEmpty()
     */
    @Override
    public boolean isEmpty() {
        return getList().isEmpty();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        return getList().hashCode();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#toArray()
     */
    @Override
    public Object[] toArray() {
        return getList().toArray();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#removeAll(java.util.Collection)
     */
    @Override
    public boolean removeAll(Collection<?> c) {
        return getList().removeAll(c);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#toArray(java.lang.Object[])
     */
    @Override
    public <T> T[] toArray(T[] a) {
        return getList().toArray(a);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#add(java.lang.Object)
     */
    @Override
    public boolean add(T e) {
        return getList().add(e);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#remove(java.lang.Object)
     */
    @Override
    public boolean remove(Object o) {
        return getList().remove(o);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#containsAll(java.util.Collection)
     */
    @Override
    public boolean containsAll(Collection<?> c) {
        return getList().containsAll(c);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#addAll(java.util.Collection)
     */
    @Override
    public boolean addAll(Collection<? extends T> c) {
        return getList().addAll(c);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#retainAll(java.util.Collection)
     */
    @Override
    public boolean retainAll(Collection<?> c) {
        return getList().retainAll(c);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#clear()
     */
    @Override
    public void clear() {
        getList().clear();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return getList().toString();
    }

    /*
     * (non-Javadoc)
     * 
     * @see org.jooq.lambda.Collectable#collect(java.util.stream.Collector)
     */
    @Override
    public <R, A> R collect(Collector<? super T, A, R> collector) {
        return stream().collect(collector);
    }

    /*
     * (non-Javadoc)
     * 
     * @see org.jooq.lambda.Collectable#count()
     */
    @Override
    public long count() {
        return this.size();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.List#addAll(int, java.util.Collection)
     */
    @Override
    public boolean addAll(int index, Collection<? extends T> c) {
        return getList().addAll(index, c);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.List#replaceAll(java.util.function.UnaryOperator)
     */
    @Override
    public void replaceAll(UnaryOperator<T> operator) {
        getList().replaceAll(operator);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#removeIf(java.util.function.Predicate)
     */
    @Override
    public boolean removeIf(Predicate<? super T> filter) {
        return getList().removeIf(filter);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.List#sort(java.util.Comparator)
     */
    @Override
    public void sort(Comparator<? super T> c) {
        getList().sort(c);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.List#get(int)
     */
    @Override
    public T get(int index) {
        return getList().get(index);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.List#set(int, java.lang.Object)
     */
    @Override
    public T set(int index, T element) {
        return getList().set(index, element);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.List#add(int, java.lang.Object)
     */
    @Override
    public void add(int index, T element) {
        getList().add(index, element);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.List#remove(int)
     */
    @Override
    public T remove(int index) {
        return getList().remove(index);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.Collection#parallelStream()
     */
    @Override
    public Stream<T> parallelStream() {
        return getList().parallelStream();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.List#indexOf(java.lang.Object)
     */
    @Override
    public int indexOf(Object o) {
        // return
        // stream().zipWithIndex().filter(t->Objects.equals(t.v1,o)).findFirst().get().v2.intValue();
        return getList().indexOf(o);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.List#lastIndexOf(java.lang.Object)
     */
    @Override
    public int lastIndexOf(Object o) {
        return getList().lastIndexOf(o);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.List#listIterator()
     */
    @Override
    public ListIterator<T> listIterator() {
        return getList().listIterator();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.util.List#listIterator(int)
     */
    @Override
    public ListIterator<T> listIterator(int index) {
        return getList().listIterator(index);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#subList(int,
     * int)
     */
    @Override
    public LazyListX<T> subList(int fromIndex, int toIndex) {
        return new LazyListX<T>(
                                getList().subList(fromIndex, toIndex), getCollector());
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Iterable#spliterator()
     */
    @Override
    public Spliterator<T> spliterator() {
        return getList().spliterator();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Comparable#compareTo(java.lang.Object)
     */
    @Override
    public int compareTo(T o) {
        if (o instanceof List) {
            List l = (List) o;
            if (this.size() == l.size()) {
                Iterator i1 = iterator();
                Iterator i2 = l.iterator();
                if (i1.hasNext()) {
                    if (i2.hasNext()) {
                        int comp = Comparator.<Comparable> naturalOrder()
                                             .compare((Comparable) i1.next(), (Comparable) i2.next());
                        if (comp != 0)
                            return comp;
                    }
                    return 1;
                } else {
                    if (i2.hasNext())
                        return -1;
                    else
                        return 0;
                }
            }
            return this.size() - ((List) o).size();
        } else
            return 1;

    }

    private List<T> getList() {
        return lazy.get();
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.reactor.collections.extensions.base.
     * AbstractFluentCollectionX#stream(reactor.core.publisher.Flux)
     */
    @Override
    public <X> LazyListX<X> stream(Flux<X> stream) {
        return new LazyListX<X>(
                                stream);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.persistent.PBagX#stream()
     */
    @Override
    public ReactiveSeq<T> stream() {
        return ReactiveSeq.fromStream(lazy.get()
                                          .stream());
    }

    @Override
    public Flux<T> flux() {
        return lazy.flux();
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#combine(java.
     * util.function.BiPredicate, java.util.function.BinaryOperator)
     */
    @Override
    public LazyListX<T> combine(BiPredicate<? super T, ? super T> predicate, BinaryOperator<T> op) {

        return (LazyListX<T>) super.combine(predicate, op);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.data.collections.extensions.standard.ListX#reverse()
     */
    @Override
    public LazyListX<T> reverse() {

        return (LazyListX<T>) super.reverse();
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#filter(java.
     * util.function.Predicate)
     */
    @Override
    public LazyListX<T> filter(Predicate<? super T> pred) {

        return (LazyListX<T>) super.filter(pred);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#map(java.util.
     * function.Function)
     */
    @Override
    public <R> LazyListX<R> map(Function<? super T, ? extends R> mapper) {

        return (LazyListX<R>) super.map(mapper);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#flatMap(java.
     * util.function.Function)
     */
    @Override
    public <R> LazyListX<R> flatMap(Function<? super T, ? extends Iterable<? extends R>> mapper) {
        return (LazyListX<R>) super.flatMap(mapper);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#limit(long)
     */
    @Override
    public LazyListX<T> limit(long num) {
        return (LazyListX<T>) super.limit(num);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#skip(long)
     */
    @Override
    public LazyListX<T> skip(long num) {
        return (LazyListX<T>) super.skip(num);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#takeRight(int)
     */
    @Override
    public LazyListX<T> takeRight(int num) {
        return (LazyListX<T>) super.takeRight(num);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#dropRight(int)
     */
    @Override
    public LazyListX<T> dropRight(int num) {
        return (LazyListX<T>) super.dropRight(num);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#takeWhile(java
     * .util.function.Predicate)
     */
    @Override
    public LazyListX<T> takeWhile(Predicate<? super T> p) {
        return (LazyListX<T>) super.takeWhile(p);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#dropWhile(java
     * .util.function.Predicate)
     */
    @Override
    public LazyListX<T> dropWhile(Predicate<? super T> p) {
        return (LazyListX<T>) super.dropWhile(p);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#takeUntil(java
     * .util.function.Predicate)
     */
    @Override
    public LazyListX<T> takeUntil(Predicate<? super T> p) {
        return (LazyListX<T>) super.takeUntil(p);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#dropUntil(java
     * .util.function.Predicate)
     */
    @Override
    public LazyListX<T> dropUntil(Predicate<? super T> p) {
        return (LazyListX<T>) super.dropUntil(p);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#trampoline(
     * java.util.function.Function)
     */
    @Override
    public <R> LazyListX<R> trampoline(Function<? super T, ? extends Trampoline<? extends R>> mapper) {
        return (LazyListX<R>) super.trampoline(mapper);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#slice(long,
     * long)
     */
    @Override
    public LazyListX<T> slice(long from, long to) {
        return (LazyListX<T>) super.slice(from, to);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#grouped(int)
     */
    @Override
    public LazyListX<ListX<T>> grouped(int groupSize) {

        return (LazyListX<ListX<T>>) super.grouped(groupSize);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#grouped(java.
     * util.function.Function, java.util.stream.Collector)
     */
    @Override
    public <K, A, D> LazyListX<Tuple2<K, D>> grouped(Function<? super T, ? extends K> classifier,
            Collector<? super T, A, D> downstream) {

        return (LazyListX) super.grouped(classifier, downstream);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#grouped(java.
     * util.function.Function)
     */
    @Override
    public <K> LazyListX<Tuple2<K, Seq<T>>> grouped(Function<? super T, ? extends K> classifier) {

        return (LazyListX) super.grouped(classifier);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#zip(java.lang.
     * Iterable)
     */
    @Override
    public <U> LazyListX<Tuple2<T, U>> zip(Iterable<? extends U> other) {

        return (LazyListX) super.zip(other);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#zip(java.lang.
     * Iterable, java.util.function.BiFunction)
     */
    @Override
    public <U, R> LazyListX<R> zip(Iterable<? extends U> other, BiFunction<? super T, ? super U, ? extends R> zipper) {

        return (LazyListX<R>) super.zip(other, zipper);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#sliding(int)
     */
    @Override
    public LazyListX<ListX<T>> sliding(int windowSize) {

        return (LazyListX<ListX<T>>) super.sliding(windowSize);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#sliding(int,
     * int)
     */
    @Override
    public LazyListX<ListX<T>> sliding(int windowSize, int increment) {

        return (LazyListX<ListX<T>>) super.sliding(windowSize, increment);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#scanLeft(com.
     * aol.cyclops.Monoid)
     */
    @Override
    public LazyListX<T> scanLeft(Monoid<T> monoid) {

        return (LazyListX<T>) super.scanLeft(monoid);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#scanLeft(java.
     * lang.Object, java.util.function.BiFunction)
     */
    @Override
    public <U> LazyListX<U> scanLeft(U seed, BiFunction<? super U, ? super T, ? extends U> function) {

        return (LazyListX<U>) super.scanLeft(seed, function);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#scanRight(com.
     * aol.cyclops.Monoid)
     */
    @Override
    public LazyListX<T> scanRight(Monoid<T> monoid) {

        return (LazyListX<T>) super.scanRight(monoid);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#scanRight(java
     * .lang.Object, java.util.function.BiFunction)
     */
    @Override
    public <U> LazyListX<U> scanRight(U identity, BiFunction<? super T, ? super U, ? extends U> combiner) {

        return (LazyListX<U>) super.scanRight(identity, combiner);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#sorted(java.
     * util.function.Function)
     */
    @Override
    public <U extends Comparable<? super U>> LazyListX<T> sorted(Function<? super T, ? extends U> function) {

        return (LazyListX<T>) super.sorted(function);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#plus(java.lang
     * .Object)
     */
    @Override
    public LazyListX<T> plus(T e) {

        return (LazyListX<T>) super.plus(e);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#plusAll(java.
     * util.Collection)
     */
    @Override
    public LazyListX<T> plusAll(Collection<? extends T> list) {

        return (LazyListX<T>) super.plusAll(list);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#minus(java.
     * lang.Object)
     */
    @Override
    public LazyListX<T> minus(Object e) {

        return (LazyListX<T>) super.minus(e);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#minusAll(java.
     * util.Collection)
     */
    @Override
    public LazyListX<T> minusAll(Collection<?> list) {

        return (LazyListX<T>) super.minusAll(list);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#plusLazy(java.
     * lang.Object)
     */
    @Override
    public LazyListX<T> plusLazy(T e) {

        return (LazyListX<T>) super.plusLazy(e);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#plusAllLazy(
     * java.util.Collection)
     */
    @Override
    public LazyListX<T> plusAllLazy(Collection<? extends T> list) {

        return (LazyListX<T>) super.plusAllLazy(list);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#minusLazy(java
     * .lang.Object)
     */
    @Override
    public LazyListX<T> minusLazy(Object e) {

        return (LazyListX<T>) super.minusLazy(e);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#minusAllLazy(
     * java.util.Collection)
     */
    @Override
    public LazyListX<T> minusAllLazy(Collection<?> list) {

        return (LazyListX<T>) super.minusAllLazy(list);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#cycle(int)
     */
    @Override
    public LazyListX<T> cycle(int times) {

        return (LazyListX<T>) super.cycle(times);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#cycle(com.aol.
     * cyclops.Monoid, int)
     */
    @Override
    public LazyListX<T> cycle(Monoid<T> m, int times) {

        return (LazyListX<T>) super.cycle(m, times);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#cycleWhile(
     * java.util.function.Predicate)
     */
    @Override
    public LazyListX<T> cycleWhile(Predicate<? super T> predicate) {

        return (LazyListX<T>) super.cycleWhile(predicate);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#cycleUntil(
     * java.util.function.Predicate)
     */
    @Override
    public LazyListX<T> cycleUntil(Predicate<? super T> predicate) {

        return (LazyListX<T>) super.cycleUntil(predicate);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#zip(org.jooq.
     * lambda.Seq)
     */
    @Override
    public <U> LazyListX<Tuple2<T, U>> zip(Seq<? extends U> other) {

        return (LazyListX) super.zip(other);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#zip3(java.util
     * .stream.Stream, java.util.stream.Stream)
     */
    @Override
    public <S, U> LazyListX<Tuple3<T, S, U>> zip3(Stream<? extends S> second, Stream<? extends U> third) {

        return (LazyListX) super.zip3(second, third);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#zip4(java.util
     * .stream.Stream, java.util.stream.Stream, java.util.stream.Stream)
     */
    @Override
    public <T2, T3, T4> LazyListX<Tuple4<T, T2, T3, T4>> zip4(Stream<? extends T2> second, Stream<? extends T3> third,
            Stream<? extends T4> fourth) {

        return (LazyListX) super.zip4(second, third, fourth);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#zipWithIndex()
     */
    @Override
    public LazyListX<Tuple2<T, Long>> zipWithIndex() {

        return (LazyListX<Tuple2<T, Long>>) super.zipWithIndex();
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#distinct()
     */
    @Override
    public LazyListX<T> distinct() {

        return (LazyListX<T>) super.distinct();
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.data.collections.extensions.standard.ListX#sorted()
     */
    @Override
    public LazyListX<T> sorted() {

        return (LazyListX<T>) super.sorted();
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#sorted(java.
     * util.Comparator)
     */
    @Override
    public LazyListX<T> sorted(Comparator<? super T> c) {

        return (LazyListX<T>) super.sorted(c);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#skipWhile(java
     * .util.function.Predicate)
     */
    @Override
    public LazyListX<T> skipWhile(Predicate<? super T> p) {

        return (LazyListX<T>) super.skipWhile(p);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#skipUntil(java
     * .util.function.Predicate)
     */
    @Override
    public LazyListX<T> skipUntil(Predicate<? super T> p) {

        return (LazyListX<T>) super.skipUntil(p);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#limitWhile(
     * java.util.function.Predicate)
     */
    @Override
    public LazyListX<T> limitWhile(Predicate<? super T> p) {

        return (LazyListX<T>) super.limitWhile(p);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#limitUntil(
     * java.util.function.Predicate)
     */
    @Override
    public LazyListX<T> limitUntil(Predicate<? super T> p) {

        return (LazyListX<T>) super.limitUntil(p);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#intersperse(
     * java.lang.Object)
     */
    @Override
    public LazyListX<T> intersperse(T value) {

        return (LazyListX<T>) super.intersperse(value);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.data.collections.extensions.standard.ListX#shuffle()
     */
    @Override
    public LazyListX<T> shuffle() {

        return (LazyListX<T>) super.shuffle();
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#skipLast(int)
     */
    @Override
    public LazyListX<T> skipLast(int num) {

        return (LazyListX<T>) super.skipLast(num);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#limitLast(int)
     */
    @Override
    public LazyListX<T> limitLast(int num) {

        return (LazyListX<T>) super.limitLast(num);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#onEmpty(java.
     * lang.Object)
     */
    @Override
    public LazyListX<T> onEmpty(T value) {

        return (LazyListX<T>) super.onEmpty(value);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#onEmptyGet(
     * java.util.function.Supplier)
     */
    @Override
    public LazyListX<T> onEmptyGet(Supplier<? extends T> supplier) {

        return (LazyListX<T>) super.onEmptyGet(supplier);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#onEmptyThrow(
     * java.util.function.Supplier)
     */
    @Override
    public <X extends Throwable> LazyListX<T> onEmptyThrow(Supplier<? extends X> supplier) {

        return (LazyListX<T>) super.onEmptyThrow(supplier);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#shuffle(java.
     * util.Random)
     */
    @Override
    public LazyListX<T> shuffle(Random random) {

        return (LazyListX<T>) super.shuffle(random);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#ofType(java.
     * lang.Class)
     */
    @Override
    public <U> LazyListX<U> ofType(Class<? extends U> type) {

        return (LazyListX<U>) super.ofType(type);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#filterNot(java
     * .util.function.Predicate)
     */
    @Override
    public LazyListX<T> filterNot(Predicate<? super T> fn) {

        return (LazyListX<T>) super.filterNot(fn);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.data.collections.extensions.standard.ListX#notNull()
     */
    @Override
    public LazyListX<T> notNull() {

        return (LazyListX<T>) super.notNull();
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#removeAll(java
     * .util.stream.Stream)
     */
    @Override
    public LazyListX<T> removeAll(Stream<? extends T> stream) {

        return (LazyListX<T>) (super.removeAll(stream));
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#removeAll(org.
     * jooq.lambda.Seq)
     */
    @Override
    public LazyListX<T> removeAll(Seq<? extends T> stream) {

        return (LazyListX<T>) super.removeAll(stream);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#removeAll(java
     * .lang.Iterable)
     */
    @Override
    public LazyListX<T> removeAll(Iterable<? extends T> it) {

        return (LazyListX<T>) super.removeAll(it);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#removeAll(java
     * .lang.Object[])
     */
    @Override
    public LazyListX<T> removeAll(T... values) {

        return (LazyListX<T>) super.removeAll(values);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#retainAll(java
     * .lang.Iterable)
     */
    @Override
    public LazyListX<T> retainAll(Iterable<? extends T> it) {

        return (LazyListX<T>) super.retainAll(it);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#retainAll(java
     * .util.stream.Stream)
     */
    @Override
    public LazyListX<T> retainAll(Stream<? extends T> stream) {

        return (LazyListX<T>) super.retainAll(stream);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#retainAll(org.
     * jooq.lambda.Seq)
     */
    @Override
    public LazyListX<T> retainAll(Seq<? extends T> stream) {

        return (LazyListX<T>) super.retainAll(stream);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#retainAll(java
     * .lang.Object[])
     */
    @Override
    public LazyListX<T> retainAll(T... values) {

        return (LazyListX<T>) super.retainAll(values);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#cast(java.lang
     * .Class)
     */
    @Override
    public <U> LazyListX<U> cast(Class<? extends U> type) {

        return (LazyListX<U>) super.cast(type);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#patternMatch(
     * java.util.function.Function, java.util.function.Supplier)
     */
    @Override
    public <R> LazyListX<R> patternMatch(Function<CheckValue1<T, R>, CheckValue1<T, R>> case1,
            Supplier<? extends R> otherwise) {

        return (LazyListX<R>) super.patternMatch(case1, otherwise);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#permutations()
     */
    @Override
    public LazyListX<ReactiveSeq<T>> permutations() {

        return (LazyListX<ReactiveSeq<T>>) super.permutations();
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#combinations(
     * int)
     */
    @Override
    public LazyListX<ReactiveSeq<T>> combinations(int size) {

        return (LazyListX<ReactiveSeq<T>>) super.combinations(size);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#combinations()
     */
    @Override
    public LazyListX<ReactiveSeq<T>> combinations() {

        return (LazyListX<ReactiveSeq<T>>) super.combinations();
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#grouped(int,
     * java.util.function.Supplier)
     */
    @Override
    public <C extends Collection<? super T>> LazyListX<C> grouped(int size, Supplier<C> supplier) {

        return (LazyListX<C>) super.grouped(size, supplier);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#groupedUntil(
     * java.util.function.Predicate)
     */
    @Override
    public LazyListX<ListX<T>> groupedUntil(Predicate<? super T> predicate) {

        return (LazyListX<ListX<T>>) super.groupedUntil(predicate);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#groupedWhile(
     * java.util.function.Predicate)
     */
    @Override
    public LazyListX<ListX<T>> groupedWhile(Predicate<? super T> predicate) {

        return (LazyListX<ListX<T>>) super.groupedWhile(predicate);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#groupedWhile(
     * java.util.function.Predicate, java.util.function.Supplier)
     */
    @Override
    public <C extends Collection<? super T>> LazyListX<C> groupedWhile(Predicate<? super T> predicate,
            Supplier<C> factory) {

        return (LazyListX<C>) super.groupedWhile(predicate, factory);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#groupedUntil(
     * java.util.function.Predicate, java.util.function.Supplier)
     */
    @Override
    public <C extends Collection<? super T>> LazyListX<C> groupedUntil(Predicate<? super T> predicate,
            Supplier<C> factory) {

        return (LazyListX<C>) super.groupedUntil(predicate, factory);
    }

    /** ListX methods **/

    /*
     * Makes a defensive copy of this ListX replacing the value at i with the
     * specified element (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.collections.extensions.standard.MutableSequenceX#with(
     * int, java.lang.Object)
     */
    public LazyListX<T> with(int i, T element) {
        return stream(Fluxes.insertAt(Fluxes.deleteBetween(flux(), i, i + 1), i, element));
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#minus(int)
     */
    @Override
    public LazyListX<T> minus(int pos) {
        remove(pos);
        return this;
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.data.collections.extensions.standard.ListX#plus(int,
     * java.lang.Object)
     */
    @Override
    public LazyListX<T> plus(int i, T e) {
        add(i, e);
        return this;
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#plusAll(int,
     * java.util.Collection)
     */
    @Override
    public LazyListX<T> plusAll(int i, Collection<? extends T> list) {
        addAll(i, list);
        return this;
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.reactor.collections.extensions.base.LazyFluentCollectionX
     * #unit(java.util.Collection)
     */
    @Override
    public <R> LazyListX<R> unit(Collection<R> col) {
        return LazyListX.fromIterable(col);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.types.Unit#unit(java.lang.Object)
     */
    @Override
    public <R> LazyListX<R> unit(R value) {
        return LazyListX.singleton(value);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.reactor.collections.extensions.base.
     * AbstractFluentCollectionX#unitIterator(java.util.Iterator)
     */
    @Override
    public <R> LazyListX<R> unitIterator(Iterator<R> it) {
        return LazyListX.fromIterable(() -> it);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.reactor.collections.extensions.base.LazyFluentCollectionX
     * #plusInOrder(java.lang.Object)
     */
    @Override
    public LazyListX<T> plusInOrder(T e) {

        return (LazyListX<T>) super.plusInOrder(e);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.reactor.collections.extensions.base.
     * AbstractFluentCollectionX#from(java.util.Collection)
     */
    @Override
    public <T1> LazyListX<T1> from(Collection<T1> c) {
        if (c instanceof List)
            return new LazyListX<T1>(
                                     (List) c, (Collector) collector);
        return new LazyListX<T1>(
                                 (List) c.stream()
                                         .collect(Collectors.toList()),
                                 (Collector) this.collector);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.reactor.collections.extensions.base.
     * AbstractFluentCollectionX#groupedStatefullyUntil(java.util.function.
     * BiPredicate)
     */
    @Override
    public LazyListX<ListX<T>> groupedStatefullyUntil(BiPredicate<ListX<? super T>, ? super T> predicate) {

        return (LazyListX<ListX<T>>) super.groupedStatefullyUntil(predicate);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.reactor.collections.extensions.base.
     * AbstractFluentCollectionX#peek(java.util.function.Consumer)
     */
    @Override
    public LazyListX<T> peek(Consumer<? super T> c) {

        return (LazyListX) super.peek(c);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.reactor.collections.extensions.base.
     * AbstractFluentCollectionX#zip(org.jooq.lambda.Seq,
     * java.util.function.BiFunction)
     */
    @Override
    public <U, R> LazyListX<R> zip(Seq<? extends U> other, BiFunction<? super T, ? super U, ? extends R> zipper) {

        return (LazyListX<R>) super.zip(other, zipper);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.reactor.collections.extensions.base.
     * AbstractFluentCollectionX#zip(java.util.stream.Stream,
     * java.util.function.BiFunction)
     */
    @Override
    public <U, R> LazyListX<R> zip(Stream<? extends U> other, BiFunction<? super T, ? super U, ? extends R> zipper) {

        return (LazyListX<R>) super.zip(other, zipper);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.reactor.collections.extensions.base.
     * AbstractFluentCollectionX#zip(java.util.stream.Stream)
     */
    @Override
    public <U> LazyListX<Tuple2<T, U>> zip(Stream<? extends U> other) {

        return (LazyListX) super.zip(other);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.aol.cyclops.reactor.collections.extensions.base.
     * AbstractFluentCollectionX#zip(java.util.function.BiFunction,
     * org.reactivestreams.Publisher)
     */
    @Override
    public <T2, R> LazyListX<R> zip(BiFunction<? super T, ? super T2, ? extends R> fn,
            Publisher<? extends T2> publisher) {

        return (LazyListX<R>) super.zip(fn, publisher);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#fromStream(
     * java.util.stream.Stream)
     */
    @Override
    public <X> LazyListX<X> fromStream(Stream<X> stream) {
        List<X> list = (List<X>) stream.collect((Collector) getCollector());
        return new LazyListX<X>(
                                list, (Collector) getCollector());
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.aol.cyclops.data.collections.extensions.standard.ListX#onEmptySwitch(
     * java.util.function.Supplier)
     */
    @Override
    public LazyListX<T> onEmptySwitch(Supplier<? extends List<T>> supplier) {
        return stream(Fluxes.onEmptySwitch(flux(), () -> Flux.fromIterable(supplier.get())));
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.LazyFluentCollectionX#materialize()
     */
    @Override
    public LazyListX<T> materialize() {
       this.lazy.get();
       return this;
    }


}
