package com.aol.cyclops.reactor.collections.extensions.standard;

import java.util.Collection;
import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import java.util.Queue;
import java.util.Random;
import java.util.Set;
import java.util.Spliterator;
import java.util.function.BiFunction;
import java.util.function.BiPredicate;
import java.util.function.BinaryOperator;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import java.util.stream.Collector;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.jooq.lambda.Seq;
import org.jooq.lambda.tuple.Tuple2;
import org.jooq.lambda.tuple.Tuple3;
import org.jooq.lambda.tuple.Tuple4;
import org.reactivestreams.Publisher;

import com.aol.cyclops.Monoid;
import com.aol.cyclops.control.Matchable.CheckValue1;
import com.aol.cyclops.control.ReactiveSeq;
import com.aol.cyclops.control.Trampoline;
import com.aol.cyclops.data.collections.extensions.standard.ListX;
import com.aol.cyclops.data.collections.extensions.standard.SetX;
import com.aol.cyclops.reactor.FluxUtils;
import com.aol.cyclops.reactor.collections.extensions.base.AbstractFluentCollectionX;
import com.aol.cyclops.reactor.collections.extensions.base.LazyFluentCollection;

import lombok.Getter;
import reactor.core.publisher.Flux;

/**
 * An extended Set type {@see java.util.Set}
 * Extended Set operations execute lazily e.g.
 * <pre>
 * {@code 
 *    LazySetX<Integer> q = LazySetX.of(1,2,3)
 *                                      .map(i->i*2);
 * }
 * </pre>
 * The map operation above is not executed immediately. It will only be executed when (if) the data inside the
 * set is accessed. This allows lazy operations to be chained and executed more efficiently e.g.
 * 
 * <pre>
 * {@code 
 *    LazySetX<Integer> q = LazySetX.of(1,2,3)
 *                                      .map(i->i*2);
 *                                      .filter(i->i<5);
 * }
 * </pre>
 * 
 * The operation above is more efficient than the equivalent operation with a SetX.
 * 
 * NB. Because LazySetX transform operations are performed Lazily, they may result in a different result 
 * than SetX operations that are performed eagerly. For example a sequence of map operations that result in
 * duplicate keys, may result in a different Set being produced.
 * 
 * @author johnmcclean
 *
 * @param <T> the type of elements held in this collection
 */
public class LazySetX<T> extends AbstractFluentCollectionX<T> implements SetX<T> {
    private final  LazyFluentCollection<T,Set<T>> lazy;
    @Getter
    private final Collector<T,?,Set<T>> collector;
    
    
    /**
     * Create a LazySetX from a Stream
     * 
     * @param stream to construct a LazySetX from
     * @return LazySetX
     */
    public static <T> LazySetX<T> fromStreamS(Stream<T> stream){
        return new LazySetX<T>(Flux.from(ReactiveSeq.fromStream(stream)));
    }
    /**
     * Create a LazySetX that contains the Integers between start and end
     * 
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range LazySetX
     */
    public static LazySetX<Integer> range(int start, int end) {
        return fromStreamS(ReactiveSeq.range(start, end));
    }

    /**
     * Create a LazySetX that contains the Longs between start and end
     * 
     * @param start
     *            Number of range to start from
     * @param end
     *            Number for range to end at
     * @return Range LazySetX
     */
    public static LazySetX<Long> rangeLong(long start, long end) {
        return fromStreamS(ReactiveSeq.rangeLong(start, end));
    }

    /**
     * Unfold a function into a LazySetX
     * 
     * <pre>
     * {@code 
     *  LazySetX.unfold(1,i->i<=6 ? Optional.of(Tuple.tuple(i,i+1)) : Optional.empty());
     * 
     * //(1,2,3,4,5)
     * 
     * }</pre>
     * 
     * @param seed Initial value 
     * @param unfolder Iteratively applied function, terminated by an empty Optional
     * @return LazySetX generated by unfolder function
     */
    public static <U, T> LazySetX<T> unfold(U seed, Function<? super U, Optional<Tuple2<T, U>>> unfolder) {
        return fromStreamS(ReactiveSeq.unfold(seed, unfolder));
    }

    /**
     * Generate a LazySetX from the provided Supplier up to the provided limit number of times
     * 
     * @param limit Max number of elements to generate
     * @param s Supplier to generate ListX elements
     * @return LazySetX generated from the provided Supplier
     */
    public static <T> LazySetX<T> generate(long limit, Supplier<T> s) {

        return fromStreamS(ReactiveSeq.generate(s)
                          .limit(limit));
    }

    /**
     * Create a LazySetX by iterative application of a function to an initial element up to the supplied limit number of times
     * 
     * @param limit Max number of elements to generate
     * @param seed Initial element
     * @param f Iteratively applied to each element to generate the next element
     * @return ListX generated by iterative application
     */
    public static <T> LazySetX<T> iterate(long limit, final T seed, final UnaryOperator<T> f) {
        return fromStreamS(ReactiveSeq.iterate(seed, f)
                          .limit(limit));
    }


    /**
     * @return A collector that generates a LazySetX
     */
    public static <T> Collector<T, ?, LazySetX<T>> lazyListXCollector() {
        return Collectors.toCollection(() -> LazySetX.of());
    }

   

    /**
     * @return An empty LazySetX
     */
    public static <T> LazySetX<T> empty() {
        return fromIterable((List<T>) ListX.<T>defaultCollector().supplier()
                                                        .get());
    }

    /**
     * Create a LazySetX from the specified values
     * <pre>
     * {@code 
     *     ListX<Integer> lazy = LazySetX.of(1,2,3,4,5);
     *     
     *     //lazily map List
     *     ListX<String> mapped = lazy.map(i->"mapped " +i); 
     *     
     *     String value = mapped.get(0); //transformation triggered now
     * }
     * </pre>
     * 
     * @param values To populate LazySetX with
     * @return LazySetX
     */
    @SafeVarargs
    public static <T> LazySetX<T> of(T... values) {
        List<T> res = (List<T>) ListX.<T>defaultCollector().supplier()
                                                  .get();
        for (T v : values)
            res.add(v);
        return fromIterable(res);
    }

    /**
     * Construct a LazySetX with a single value
     * <pre>
     * {@code 
     *    ListX<Integer> lazy = LazySetX.singleton(5);
     *    
     * }
     * </pre>
     * 
     * 
     * @param value To populate LazySetX with
     * @return LazySetX with a single value
     */
    public static <T> LazySetX<T> singleton(T value) {
        return LazySetX.<T> of(value);
    }

    /**
     * Construct a LazySetX from an Publisher
     * 
     * @param publisher
     *            to construct LazySetX from
     * @return ListX
     */
    public static <T> LazySetX<T> fromPublisher(Publisher<? extends T> publisher) {
        return fromStreamS(ReactiveSeq.fromPublisher((Publisher<T>) publisher));
    }

    /**
     * Construct LazySetX from an Iterable
     * 
     * @param it to construct LazySetX from
     * @return LazySetX from Iterable
     */
    public static <T> LazySetX<T> fromIterable(Iterable<T> it) {
        return fromIterable(SetX.<T>defaultCollector(), it);
    }

    /**
     * Construct a LazySetX from an Iterable, using the specified Collector.
     * 
     * @param collector To generate Lists from, this can be used to create mutable vs immutable Lists (for example), or control List type (ArrayList, LinkedList)
     * @param it Iterable to construct LazySetX from
     * @return Newly constructed LazySetX
     */
    public static <T> LazySetX<T> fromIterable(Collector<T, ?, Set<T>> collector, Iterable<T> it) {
        if (it instanceof LazySetX)
            return (LazySetX<T>) it;
       
        if (it instanceof Set)
            return new LazySetX<T>(
                                    (Set<T>) it, collector);
        return new LazySetX<T>(
                                Flux.fromIterable(it),
                                collector);
    }
    private LazySetX(Set<T> list,Collector<T,?,Set<T>> collector){
        this.lazy = new LazyCollection<>(list,null,collector);
        this.collector=  collector;
    }
    
    private LazySetX(Set<T> list){
        this.collector = SetX.defaultCollector();
        this.lazy = new LazyCollection<T,Set<T>>(list,null,collector);
    }
    private LazySetX(Flux<T> stream,Collector<T,?,Set<T>> collector){
        
        this.collector = collector;
        this.lazy = new LazyCollection<>(null,stream,collector);
    }
    private LazySetX(Flux<T> stream){
        
        this.collector = SetX.defaultCollector();
        this.lazy = new LazyCollection<>(null,stream,collector);
    }
    private LazySetX(){
        this.collector = SetX.defaultCollector();
        this.lazy = new LazyCollection<>((Set)this.collector.supplier().get(),null,collector);
    }
    
    /* (non-Javadoc)
     * @see java.lang.Iterable#forEach(java.util.function.Consumer)
     */
    @Override
    public void forEach(Consumer<? super T> action) {
        getSet().forEach(action);
    }

    /* (non-Javadoc)
     * @see java.lang.Iterable#iterator()
     */
    @Override
    public Iterator<T> iterator() {
        return getSet().iterator();
    }

    /* (non-Javadoc)
     * @see java.util.Collection#size()
     */
    @Override
    public int size() {
        return getSet().size();
    }

    /* (non-Javadoc)
     * @see java.util.Collection#contains(java.lang.Object)
     */
    @Override
    public boolean contains(Object e) {
        return getSet().contains(e);
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object o) {
        return getSet().equals(o);
    }



    /* (non-Javadoc)
     * @see java.util.Collection#isEmpty()
     */
    @Override
    public boolean isEmpty() {
        return getSet().isEmpty();
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        return getSet().hashCode();
    }

    /* (non-Javadoc)
     * @see java.util.Collection#toArray()
     */
    @Override
    public Object[] toArray() {
        return getSet().toArray();
    }

    /* (non-Javadoc)
     * @see java.util.Collection#removeAll(java.util.Collection)
     */
    @Override
    public boolean removeAll(Collection<?> c) {
        return getSet().removeAll(c);
    }

    /* (non-Javadoc)
     * @see java.util.Collection#toArray(java.lang.Object[])
     */
    @Override
    public <T> T[] toArray(T[] a) {
        return getSet().toArray(a);
    }

    /* (non-Javadoc)
     * @see java.util.Collection#add(java.lang.Object)
     */
    @Override
    public boolean add(T e) {
        return getSet().add(e);
    }

    /* (non-Javadoc)
     * @see java.util.Collection#remove(java.lang.Object)
     */
    @Override
    public boolean remove(Object o) {
        return getSet().remove(o);
    }

    /* (non-Javadoc)
     * @see java.util.Collection#containsAll(java.util.Collection)
     */
    @Override
    public boolean containsAll(Collection<?> c) {
        return getSet().containsAll(c);
    }

    /* (non-Javadoc)
     * @see java.util.Collection#addAll(java.util.Collection)
     */
    @Override
    public boolean addAll(Collection<? extends T> c) {
        return getSet().addAll(c);
    }

    /* (non-Javadoc)
     * @see java.util.Collection#retainAll(java.util.Collection)
     */
    @Override
    public boolean retainAll(Collection<?> c) {
        return getSet().retainAll(c);
    }

    /* (non-Javadoc)
     * @see java.util.Collection#clear()
     */
    @Override
    public void clear() {
        getSet().clear();
    }

    
    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return getSet().toString();
    }

    /* (non-Javadoc)
     * @see org.jooq.lambda.Collectable#collect(java.util.stream.Collector)
     */
    @Override
    public <R, A> R collect(Collector<? super T, A, R> collector) {
        return stream().collect(collector);
    }

    /* (non-Javadoc)
     * @see org.jooq.lambda.Collectable#count()
     */
    @Override
    public long count() {
        return this.size();
    }
    
    /* (non-Javadoc)
     * @see java.util.Collection#removeIf(java.util.function.Predicate)
     */
    @Override
    public  boolean removeIf(Predicate<? super T> filter) {
        return getSet().removeIf(filter);
    }
   
    
    /* (non-Javadoc)
     * @see java.util.Collection#parallelStream()
     */
    @Override
    public  Stream<T> parallelStream() {
        return getSet().parallelStream();
    }
    
    
  
    /* (non-Javadoc)
     * @see java.lang.Iterable#spliterator()
     */
    @Override
    public Spliterator<T> spliterator() {
        return getSet().spliterator();
    }
    
    private Set<T> getSet() {
        return lazy.get();
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.AbstractFluentCollectionX#stream(reactor.core.publisher.Flux)
     */
    @Override
    public <X> LazySetX<X> stream(Flux<X> stream){
        return new LazySetX<X>(stream);
    }
   
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.persistent.PBagX#stream()
     */
    @Override
    public ReactiveSeq<T> stream() {
        return ReactiveSeq.fromStream(lazy.get().stream());
    }
    @Override
    public Flux<T> flux() {
        return lazy.stream();
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#combine(java.util.function.BiPredicate, java.util.function.BinaryOperator)
     */
    @Override
    public LazySetX<T> combine(BiPredicate<? super T, ? super T> predicate, BinaryOperator<T> op) {
       
        return (LazySetX<T>)super.combine(predicate, op);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#reverse()
     */
    @Override
    public LazySetX<T> reverse() {
       
        return(LazySetX<T>)super.reverse();
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#filter(java.util.function.Predicate)
     */
    @Override
    public LazySetX<T> filter(Predicate<? super T> pred) {
       
        return (LazySetX<T>)super.filter(pred);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#map(java.util.function.Function)
     */
    @Override
    public <R> LazySetX<R> map(Function<? super T, ? extends R> mapper) {
       
        return (LazySetX<R>)super.map(mapper);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#flatMap(java.util.function.Function)
     */
    @Override
    public <R> LazySetX<R> flatMap(Function<? super T, ? extends Iterable<? extends R>> mapper) {
       return (LazySetX<R>)super.flatMap(mapper);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#limit(long)
     */
    @Override
    public LazySetX<T> limit(long num) {
       return (LazySetX<T>)super.limit(num);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#skip(long)
     */
    @Override
    public LazySetX<T> skip(long num) {
       return (LazySetX<T>)super.skip(num);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#takeRight(int)
     */
    @Override
    public LazySetX<T> takeRight(int num) {
       return (LazySetX<T>)super.takeRight(num);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#dropRight(int)
     */
    @Override
    public LazySetX<T> dropRight(int num) {
       return (LazySetX<T>)super.dropRight(num);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#takeWhile(java.util.function.Predicate)
     */
    @Override
    public LazySetX<T> takeWhile(Predicate<? super T> p) {
       return (LazySetX<T>)super.takeWhile(p);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#dropWhile(java.util.function.Predicate)
     */
    @Override
    public LazySetX<T> dropWhile(Predicate<? super T> p) {
       return (LazySetX<T>)super.dropWhile(p);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#takeUntil(java.util.function.Predicate)
     */
    @Override
    public LazySetX<T> takeUntil(Predicate<? super T> p) {
       return (LazySetX<T>)super.takeUntil(p);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#dropUntil(java.util.function.Predicate)
     */
    @Override
    public LazySetX<T> dropUntil(Predicate<? super T> p) {
       return(LazySetX<T>)super.dropUntil(p);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#trampoline(java.util.function.Function)
     */
    @Override
    public <R> LazySetX<R> trampoline(Function<? super T, ? extends Trampoline<? extends R>> mapper) {
       return (LazySetX<R>)super.trampoline(mapper);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#slice(long, long)
     */
    @Override
    public LazySetX<T> slice(long from, long to) {
       return (LazySetX<T>)super.slice(from, to);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#grouped(int)
     */
    @Override
    public LazySetX<ListX<T>> grouped(int groupSize) {
       
        return (LazySetX<ListX<T>>)super.grouped(groupSize);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#grouped(java.util.function.Function, java.util.stream.Collector)
     */
    @Override
    public <K, A, D> LazySetX<Tuple2<K, D>> grouped(Function<? super T, ? extends K> classifier,
            Collector<? super T, A, D> downstream) {
       
        return (LazySetX)super.grouped(classifier, downstream);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#grouped(java.util.function.Function)
     */
    @Override
    public <K> LazySetX<Tuple2<K, Seq<T>>> grouped(Function<? super T, ? extends K> classifier) {
       
        return (LazySetX)super.grouped(classifier);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#zip(java.lang.Iterable)
     */
    @Override
    public <U> LazySetX<Tuple2<T, U>> zip(Iterable<? extends U> other) {
       
        return (LazySetX)super.zip(other);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#zip(java.lang.Iterable, java.util.function.BiFunction)
     */
    @Override
    public <U, R> LazySetX<R> zip(Iterable<? extends U> other, BiFunction<? super T, ? super U, ? extends R> zipper) {
       
        return (LazySetX<R>)super.zip(other, zipper);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#sliding(int)
     */
    @Override
    public LazySetX<ListX<T>> sliding(int windowSize) {
       
        return (LazySetX<ListX<T>>)super.sliding(windowSize);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#sliding(int, int)
     */
    @Override
    public LazySetX<ListX<T>> sliding(int windowSize, int increment) {
       
        return (LazySetX<ListX<T>>)super.sliding(windowSize, increment);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#scanLeft(com.aol.cyclops.Monoid)
     */
    @Override
    public LazySetX<T> scanLeft(Monoid<T> monoid) {
       
        return (LazySetX<T>)super.scanLeft(monoid);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#scanLeft(java.lang.Object, java.util.function.BiFunction)
     */
    @Override
    public <U> LazySetX<U> scanLeft(U seed, BiFunction<? super U, ? super T, ? extends U> function) {
       
        return (LazySetX<U>) super.scanLeft(seed, function);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#scanRight(com.aol.cyclops.Monoid)
     */
    @Override
    public LazySetX<T> scanRight(Monoid<T> monoid) {
       
        return (LazySetX<T>)super.scanRight(monoid);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#scanRight(java.lang.Object, java.util.function.BiFunction)
     */
    @Override
    public <U> LazySetX<U> scanRight(U identity, BiFunction<? super T, ? super U, ? extends U> combiner) {
       
        return (LazySetX<U>)super.scanRight(identity, combiner);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#sorted(java.util.function.Function)
     */
    @Override
    public <U extends Comparable<? super U>> LazySetX<T> sorted(Function<? super T, ? extends U> function) {
       
        return (LazySetX<T>)super.sorted(function);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#plus(java.lang.Object)
     */
    @Override
    public LazySetX<T> plus(T e) {
       
        return (LazySetX<T>)super.plus(e);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#plusAll(java.util.Collection)
     */
    @Override
    public LazySetX<T> plusAll(Collection<? extends T> list) {
       
        return (LazySetX<T>)super.plusAll(list);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#minus(java.lang.Object)
     */
    @Override
    public LazySetX<T> minus(Object e) {
       
        return (LazySetX<T>)super.minus(e);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#minusAll(java.util.Collection)
     */
    @Override
    public LazySetX<T> minusAll(Collection<?> list) {
       
        return (LazySetX<T>)super.minusAll(list);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#plusLazy(java.lang.Object)
     */
    @Override
    public LazySetX<T> plusLazy(T e) {
       
        return (LazySetX<T>)super.plusLazy(e);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#plusAllLazy(java.util.Collection)
     */
    @Override
    public LazySetX<T> plusAllLazy(Collection<? extends T> list) {
       
        return (LazySetX<T>)super.plusAllLazy(list);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#minusLazy(java.lang.Object)
     */
    @Override
    public LazySetX<T> minusLazy(Object e) {
       
        return (LazySetX<T>)super.minusLazy(e);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#minusAllLazy(java.util.Collection)
     */
    @Override
    public LazySetX<T> minusAllLazy(Collection<?> list) {
       
        return (LazySetX<T>)super.minusAllLazy(list);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#cycle(int)
     */
    @Override
    public LazyListX<T> cycle(int times) {
        return LazyListX.fromPublisher(this.flux()
                                       .repeat(times));
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#cycle(com.aol.cyclops.Monoid, int)
     */
    @Override
    public LazyListX<T> cycle(Monoid<T> m, int times) {
        return LazyListX.fromPublisher(FluxUtils.cycle(flux(), m, times));
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#cycleWhile(java.util.function.Predicate)
     */
    @Override
    public LazyListX<T> cycleWhile(Predicate<? super T> predicate) {
       
        return LazyListX.fromPublisher(FluxUtils.cycleWhile(flux(),predicate));
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#cycleUntil(java.util.function.Predicate)
     */
    @Override
    public LazyListX<T> cycleUntil(Predicate<? super T> predicate) {
       
        return LazyListX.fromPublisher(FluxUtils.cycleUntil(flux(),predicate));
    }
    
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#zip(org.jooq.lambda.Seq)
     */
    @Override
    public <U> LazySetX<Tuple2<T, U>> zip(Seq<? extends U> other) {
       
        return (LazySetX)super.zip(other);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#zip3(java.util.stream.Stream, java.util.stream.Stream)
     */
    @Override
    public <S, U> LazySetX<Tuple3<T, S, U>> zip3(Stream<? extends S> second, Stream<? extends U> third) {
       
        return (LazySetX)super.zip3(second, third);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#zip4(java.util.stream.Stream, java.util.stream.Stream, java.util.stream.Stream)
     */
    @Override
    public <T2, T3, T4> LazySetX<Tuple4<T, T2, T3, T4>> zip4(Stream<? extends T2> second, Stream<? extends T3> third,
            Stream<? extends T4> fourth) {
       
        return (LazySetX)super.zip4(second, third, fourth);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#zipWithIndex()
     */
    @Override
    public LazySetX<Tuple2<T, Long>> zipWithIndex() {
       
        return (LazySetX<Tuple2<T, Long>>)super.zipWithIndex();
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#distinct()
     */
    @Override
    public LazySetX<T> distinct() {
       
        return (LazySetX<T>)super.distinct();
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#sorted()
     */
    @Override
    public LazySetX<T> sorted() {
       
        return (LazySetX<T>)super.sorted();
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#sorted(java.util.Comparator)
     */
    @Override
    public LazySetX<T> sorted(Comparator<? super T> c) {
       
        return (LazySetX<T>)super.sorted(c);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#skipWhile(java.util.function.Predicate)
     */
    @Override
    public LazySetX<T> skipWhile(Predicate<? super T> p) {
       
        return (LazySetX<T>)super.skipWhile(p);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#skipUntil(java.util.function.Predicate)
     */
    @Override
    public LazySetX<T> skipUntil(Predicate<? super T> p) {
       
        return (LazySetX<T>)super.skipUntil(p);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#limitWhile(java.util.function.Predicate)
     */
    @Override
    public LazySetX<T> limitWhile(Predicate<? super T> p) {
       
        return (LazySetX<T>)super.limitWhile(p);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#limitUntil(java.util.function.Predicate)
     */
    @Override
    public LazySetX<T> limitUntil(Predicate<? super T> p) {
       
        return (LazySetX<T>)super.limitUntil(p);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#intersperse(java.lang.Object)
     */
    @Override
    public LazySetX<T> intersperse(T value) {
       
        return (LazySetX<T>)super.intersperse(value);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#shuffle()
     */
    @Override
    public LazySetX<T> shuffle() {
       
        return (LazySetX<T>)super.shuffle();
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#skipLast(int)
     */
    @Override
    public LazySetX<T> skipLast(int num) {
       
        return (LazySetX<T>)super.skipLast(num);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#limitLast(int)
     */
    @Override
    public LazySetX<T> limitLast(int num) {
       
        return (LazySetX<T>)super.limitLast(num);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#onEmpty(java.lang.Object)
     */
    @Override
    public LazySetX<T> onEmpty(T value) {
       
        return (LazySetX<T>)super.onEmpty(value);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#onEmptyGet(java.util.function.Supplier)
     */
    @Override
    public LazySetX<T> onEmptyGet(Supplier<? extends T> supplier) {
       
        return (LazySetX<T>)super.onEmptyGet(supplier);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#onEmptyThrow(java.util.function.Supplier)
     */
    @Override
    public <X extends Throwable> LazySetX<T> onEmptyThrow(Supplier<? extends X> supplier) {
       
        return (LazySetX<T>)super.onEmptyThrow(supplier);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#shuffle(java.util.Random)
     */
    @Override
    public LazySetX<T> shuffle(Random random) {
       
        return (LazySetX<T>)super.shuffle(random);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#ofType(java.lang.Class)
     */
    @Override
    public <U> LazySetX<U> ofType(Class<? extends U> type) {
       
        return (LazySetX<U>)super.ofType(type);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#filterNot(java.util.function.Predicate)
     */
    @Override
    public LazySetX<T> filterNot(Predicate<? super T> fn) {
       
        return (LazySetX<T>)super.filterNot(fn);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#notNull()
     */
    @Override
    public LazySetX<T> notNull() {
       
        return (LazySetX<T>)super.notNull();
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#removeAll(java.util.stream.Stream)
     */
    @Override
    public LazySetX<T> removeAll(Stream<? extends T> stream) {
       
        return (LazySetX<T>)(super.removeAll(stream));
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#removeAll(org.jooq.lambda.Seq)
     */
    @Override
    public LazySetX<T> removeAll(Seq<? extends T> stream) {
       
        return (LazySetX<T>)super.removeAll(stream);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#removeAll(java.lang.Iterable)
     */
    @Override
    public LazySetX<T> removeAll(Iterable<? extends T> it) {
       
        return (LazySetX<T>)super.removeAll(it);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#removeAll(java.lang.Object[])
     */
    @Override
    public LazySetX<T> removeAll(T... values) {
       
        return (LazySetX<T>)super.removeAll(values);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#retainAll(java.lang.Iterable)
     */
    @Override
    public LazySetX<T> retainAll(Iterable<? extends T> it) {
       
        return (LazySetX<T>)super.retainAll(it);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#retainAll(java.util.stream.Stream)
     */
    @Override
    public LazySetX<T> retainAll(Stream<? extends T> stream) {
       
        return (LazySetX<T>)super.retainAll(stream);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#retainAll(org.jooq.lambda.Seq)
     */
    @Override
    public LazySetX<T> retainAll(Seq<? extends T> stream) {
       
        return (LazySetX<T>)super.retainAll(stream);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#retainAll(java.lang.Object[])
     */
    @Override
    public LazySetX<T> retainAll(T... values) {
       
        return (LazySetX<T>)super.retainAll(values);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#cast(java.lang.Class)
     */
    @Override
    public <U> LazySetX<U> cast(Class<? extends U> type) {
       
        return (LazySetX<U>)super.cast(type);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#patternMatch(java.util.function.Function, java.util.function.Supplier)
     */
    @Override
    public <R> LazySetX<R> patternMatch(Function<CheckValue1<T, R>, CheckValue1<T, R>> case1,
            Supplier<? extends R> otherwise) {
       
        return (LazySetX<R>)super.patternMatch(case1, otherwise);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#permutations()
     */
    @Override
    public LazySetX<ReactiveSeq<T>> permutations() {
       
        return (LazySetX<ReactiveSeq<T>>)super.permutations();
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#combinations(int)
     */
    @Override
    public LazySetX<ReactiveSeq<T>> combinations(int size) {
       
        return (LazySetX<ReactiveSeq<T>>)super.combinations(size);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#combinations()
     */
    @Override
    public LazySetX<ReactiveSeq<T>> combinations() {
       
        return (LazySetX<ReactiveSeq<T>>)super.combinations();
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#grouped(int, java.util.function.Supplier)
     */
    @Override
    public <C extends Collection<? super T>> LazySetX<C> grouped(int size, Supplier<C> supplier) {
       
        return (LazySetX<C>)super.grouped(size, supplier);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#groupedUntil(java.util.function.Predicate)
     */
    @Override
    public LazySetX<ListX<T>> groupedUntil(Predicate<? super T> predicate) {
       
        return (LazySetX<ListX<T>>)super.groupedUntil(predicate);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#groupedWhile(java.util.function.Predicate)
     */
    @Override
    public LazySetX<ListX<T>> groupedWhile(Predicate<? super T> predicate) {
       
        return (LazySetX<ListX<T>>)super.groupedWhile(predicate);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#groupedWhile(java.util.function.Predicate, java.util.function.Supplier)
     */
    @Override
    public <C extends Collection<? super T>> LazySetX<C> groupedWhile(Predicate<? super T> predicate,
            Supplier<C> factory) {
        
        return (LazySetX<C>)super.groupedWhile(predicate, factory);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#groupedUntil(java.util.function.Predicate, java.util.function.Supplier)
     */
    @Override
    public <C extends Collection<? super T>> LazySetX<C> groupedUntil(Predicate<? super T> predicate,
            Supplier<C> factory) {
        
        return (LazySetX<C>)super.groupedUntil(predicate, factory);
    }
   
    /** SetX methods **/

    /* Makes a defensive copy of this SetX replacing the value at i with the specified element
     *  (non-Javadoc)
     * @see com.aol.cyclops.collections.extensions.standard.MutableSequenceX#with(int, java.lang.Object)
     */
    public LazySetX<T> with(int i,T element){
        return stream( FluxUtils.insertAt(FluxUtils.deleteBetween(flux(),i, i+1),i,element)) ;
    }
    
    
    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.LazyFluentCollectionX#unit(java.util.Collection)
     */
    @Override
    public <R> LazySetX<R> unit(Collection<R> col){
        return LazySetX.fromIterable(col);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.types.Unit#unit(java.lang.Object)
     */
    @Override
    public  <R> LazySetX<R> unit(R value){
        return LazySetX.singleton(value);
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.AbstractFluentCollectionX#unitIterator(java.util.Iterator)
     */
    @Override
    public <R> LazySetX<R> unitIterator(Iterator<R> it){
        return LazySetX.fromIterable(()->it);
    }

    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.LazyFluentCollectionX#plusInOrder(java.lang.Object)
     */
    @Override
    public LazySetX<T> plusInOrder(T e) {
        
        return (LazySetX<T>)super.plusInOrder(e);
    }
    

    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.AbstractFluentCollectionX#from(java.util.Collection)
     */
    @Override
    public <T1> LazySetX<T1> from(Collection<T1> c) {
        if(c instanceof List)
            return new LazySetX<T1>((Set)c,(Collector)collector);
      return new LazySetX<T1>((Set)c.stream().collect(SetX.defaultCollector()),(Collector)this.collector);
    }

    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.AbstractFluentCollectionX#groupedStatefullyUntil(java.util.function.BiPredicate)
     */
    @Override
    public LazySetX<ListX<T>> groupedStatefullyUntil(BiPredicate<ListX<? super T>, ? super T> predicate) {
        
        return (LazySetX<ListX<T>>)super.groupedStatefullyUntil(predicate);
    }

    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.AbstractFluentCollectionX#peek(java.util.function.Consumer)
     */
    @Override
    public LazySetX<T> peek(Consumer<? super T> c) {
        
        return (LazySetX)super.peek(c);
    }

    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.AbstractFluentCollectionX#zip(org.jooq.lambda.Seq, java.util.function.BiFunction)
     */
    @Override
    public <U, R> LazySetX<R> zip(Seq<? extends U> other,
            BiFunction<? super T, ? super U, ? extends R> zipper) {
        
        return (LazySetX<R>)super.zip(other, zipper);
    }

    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.AbstractFluentCollectionX#zip(java.util.stream.Stream, java.util.function.BiFunction)
     */
    @Override
    public <U, R> LazySetX<R> zip(Stream<? extends U> other,
            BiFunction<? super T, ? super U, ? extends R> zipper) {
      
        return (LazySetX<R>)super.zip(other, zipper);
    }

    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.AbstractFluentCollectionX#zip(java.util.stream.Stream)
     */
    @Override
    public <U> LazySetX<Tuple2<T, U>> zip(Stream<? extends U> other) {
        
        return (LazySetX)super.zip(other);
    }

    /* (non-Javadoc)
     * @see com.aol.cyclops.reactor.collections.extensions.base.AbstractFluentCollectionX#zip(java.util.function.BiFunction, org.reactivestreams.Publisher)
     */
    @Override
    public <T2, R> LazySetX<R> zip(BiFunction<? super T, ? super T2, ? extends R> fn,
            Publisher<? extends T2> publisher) {
       
        return (LazySetX<R>)super.zip(fn, publisher);
    }
 
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#fromStream(java.util.stream.Stream)
     */
    @Override
    public <X> LazySetX<X> fromStream(Stream<X> stream) {
        Set<X> list = (Set<X>) stream.collect((Collector)getCollector());
        return new LazySetX<X>(list, (Collector)getCollector());
    }
    /* (non-Javadoc)
     * @see com.aol.cyclops.data.collections.extensions.standard.SetX#onEmptySwitch(java.util.function.Supplier)
     */
    @Override
    public LazySetX<T> onEmptySwitch(Supplier<? extends Set<T>> supplier) {
        return stream(FluxUtils.onEmptySwitch(flux(), ()->Flux.fromIterable(supplier.get())));
    }
    
   
   
    
}
